### ISSUE TITLE
Native Script 3 de diciembre 2015 - via Hangout

### ISSUE THREAD

**Issue by lporras** [Noders/Meetups#1]
-[NativeScript](http://www.telerik.com/nativescript) es un framework Open Source que permite usar JavaScript para crear aplicaciones móviles nativas que utilizan plataformas específicas y llamadas nativas a la API. Es compatible con iOS, Android, y pronto de Windows Universal. En esta charla, aprenderás cómo construir una aplicación móvil nativa con sólo un poco de JavaScript y XML.

charlista:

[Sebastian Witalec](https://twitter.com/sebawita) es un evangelista técnico con 8 años de experiencia en ingeniería de software y arquitectura. Es un apasionado por todo tipo de tecnologías, sin embargo NativeScript es su favorito. Está trabajando en estrecha colaboración con el equipo de producción de NativeScript para ayudar a conectar a la comunidad con los desarrolladores. Sebastián vive en Londres, Reino Unido y trabaja activamente con varias comunidades Dev en el área y en Europa en general.

**Comment by Xabadu** [comment]
Confirmada.
