### ISSUE TITLE
Lighting: React Hooks

### ISSUE THREAD

**Issue by highercomve** [Noders/Meetups#100]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [ ] Keynote (20 a 30 minutos)
- [X] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?

Sergio Marin

## ¿Cuál es el título de tu charla?
Estoy enganchado con los Hooks de React

Introduccion al uso de React Hooks :)

## Danos una descripción de tu charla (20 palabras)
Introduccion a como usar React Hooks y como reescribir nuestros componentes actuales

## ¿Tienes alguna red social donde podamos contactarte?
twitter: @highercomve

## ¿Representas a alguna compañía o empresa?
No

## ¿Qué tipo de conector tiene tu notebook?

- [ ] HDMI
- [ X ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?
La idea de la lighting es hablar de lo que se habla en este articulo
https://medium.com/@highercomve/why-im-excited-with-react-hooks-5a8601ac43f7

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by rodrigoAdones** [comment]
Hola Sergio

Muchas gracias por interesarte en hacer una lightning talk.

Este mes tenemos programado hacerla el jueves 21, seria genial que expusieses ese día.

Me confirmas si te parece, o si te interesa mas otra fecha

Saludos

**Comment by highercomve** [comment]
Hola @L0rdKras 

Si, me parece perfecto el 21 no hay problemas! 👍 

Saludos

**Comment by rodrigoAdones** [comment]
Buenísimo!!

Gracias por confirmar, estamos en contacto.

**Comment by rodrigoAdones** [comment]
Sergio, disculpa pero no podremos realizar el meetup este mes.

Te pido mil disculpas por cualquier inconveniente provocado por la cancelación.

Quería saber si puedes dar la charla en el meetup de Marzo, quedo atento a tu respuesta.

Saludos

**Comment by highercomve** [comment]
Hola!,

Por supuesto no hay problemas, nos vemos en marzo.

Avisen cuando y nos vemos ahí 

Saludos

**Comment by rodrigoAdones** [comment]
Buenas

Ya confirmamos el meetup para el 14 de marzo, sera en las oficinas de ComparaOnline

Puedes exponer en esa fecha? espero tu confirmación

Saludos

**Comment by highercomve** [comment]
Si no hay Problema xD

**Comment by rodrigoAdones** [comment]
Buenísima

Nos vemos el 14

Saludos
