### ISSUE TITLE
Sabor Digital

### ISSUE THREAD

**Issue by CarlosHWolox** [Noders/Meetups#101]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [X ] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Carlos Luis Hernández

## ¿Cuál es el título de tu charla?
El Sabor Digital

## Danos una descripción de tu charla (20 palabras)
Importancia de animaciones, de enfatizar en que un producto no es solo funcionalidad sino estetica y ver como estamos en un gran momento para los front-end para dar este paso.

## ¿Tienes alguna red social donde podamos contactarte?
Twitter: @Jeuiop

## ¿Representas a alguna compañía o empresa?
Wolox

## ¿Qué tipo de conector tiene tu notebook?

- [ ] HDMI
- [X] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by rodrigoAdones** [comment]
Hola Carlos

Primero, disculpa la demora en contactarte, tuvimos algunos problemas organizando el meetup.

Nos gustaría saber si puedes dar tu charla el día jueves 16 de Mayo.

Quedo atento a tu respuesta.

Saludos.
