### ISSUE TITLE
Creando Skills de Alexa con Serverless Framework y Node

### ISSUE THREAD

**Issue by nicoavila** [Noders/Meetups#102]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Nicolás Ávila

## ¿Cuál es el título de tu charla?
Creando Skills de Alexa con Serverless Framework y Node

## Danos una descripción de tu charla (20 palabras)
Aprenderemos a construir una skill de [Alexa](https://www.youtube.com/watch?v=UOEIH2l9z7c) básica usando NodeJS y [Serverless Framework](https://serverless.com/)

## ¿Tienes alguna red social donde podamos contactarte?
Twitter: [@nicoavila_a](https://twitter.com/nicoavila_a)
Medium: [@nicoavila_a](https://medium.com/@nicoavila_a)
Github: [@nicoavila](https://github.com/nicoavila)

## ¿Representas a alguna compañía o empresa?
No

## ¿Qué tipo de conector tiene tu notebook?

- [x] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by rodrigoAdones** [comment]
Hola Nico

Gracias por interesarte en dar nuevamente una charla para nuestra comunidad.

Queríamos saber si puedes darla en el meetup del jueves 16 de mayo

Quedo atento a tu respuesta

Saludos.

**Comment by nicoavila** [comment]
Hola @L0rdKras! 
Super, me anoto para este Jueves 16 con la charla.
Saludos 😄

**Comment by nicoavila** [comment]
Hola a todos! Adjunto mis slides para el Meetup de hoy: [Slides](https://nicoavila.s3.amazonaws.com/slides/Noders-20190516-Creando-Skills-de-Alexa-con-Serverless-Framework-y-Node.pdf)
