### ISSUE TITLE
 Progressive web apps con QCObjects 

### ISSUE THREAD

**Issue by jeanmachuca** [Noders/Meetups#103]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x ] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Jean Machuca 

## ¿Cuál es el título de tu charla?

Introducción al desarrollo de progressive web apps con QCObjects

## Danos una descripción de tu charla (20 palabras)

QCObjects es una tecnología de interfaz de usuario de código abierto (Open Source) basada en JavaScript que permite a un desarrollador codificar la web, dispositivos móviles y dispositivos de escritorio en un ámbito de componentes cargados en tiempo de ejecución. Está disponible para IDE Atom y Visual Studio Code. En este keynote les mostraré lo rápido que puede ser un desarrollo basado en una herramienta pensada en la performance y organización del código fuente.
Nota al pie: Producto Chileno.

## ¿Tienes alguna red social donde podamos contactarte?

https://linkedin.com/in/jeanmachuca

## ¿Representas a alguna compañía o empresa?
QuickCorp

## ¿Qué tipo de conector tiene tu notebook?

- [x ] HDMI (tengo adaptador)
- [x ] Mini DisplayPort (MacBook pro mid2012)
- [ x] VGA (tengo adaptador)

## ¿Quieres agregar algo más?

QCObjects será lanzado al mercado mundial en el RISEConf Hong Kong 2019 como alternativa a los actuales frameworks reactivos presentes en el mercado (Angular, React, Vue, etc). La comunidad de desarrolladores en torno a QCObjects va creciendo poco a poco y quisiera poder hacer partícipe a los desarrolladores de este meetup de esta nueva revolución. QuickCorp es primera empresa de Latinoamérica en presentar un proyecto de clase mundial categoría ALPHA Startup en RISEConf Hong Kong 2019. RISE atrae las startups más dinámicas del mundo. Como ejemplo: Hanson Robotics y su robot Sophia (AI avanzada) se mostraron al mundo el mismo evento. En Hong Kong nos espera el desafío de mostrar a inversionistas globales cómo nuestra tecnología competirá a la par con otras actualmente apadrinadas por Google, Microsoft y otras empresas de clase mundial. Por lo que cualquier aporte, ya sea como sponsor, beta tester o simplemente feedback de uso, será enormemente agradecido. Para contactarse conmigo directamente pueden escribir a jean@quickcorp.cl y estoy escuchando muy entusiasmado todas las propuestas de participación. Muchas gracias! 

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by rodrigoAdones** [comment]
Hola Jean

Nos alegra mucho que quieras dar una charla en el meetup de Noders.

Disculpa la demora en responder, hemos estado algo ocupados pero ya estamos retomando las actividades.

Quisiera saber si puedes presentar el jueves 18 de Julio, me confirmas tu disponibilidad.

Nuevamente gracias por tu interés.

Saludos.

**Comment by jeanmachuca** [comment]
Hola! Muchas gracias! Me encuentro aún en Hong Kong por lo que estaré disponible los primeros días de agosto para exponer en Chile. Saludos

**Comment by rodrigoAdones** [comment]
Excelente, te confirmamos la fecha del meetup de agosto para que coordinemos tu charla.

Saludos.

**Comment by rodrigoAdones** [comment]
Hola @jeanmachuca 

El meetup sera la próxima semana, el jueves 22 en las oficinas de comparaonline

Quería confirmar si puedes presentar tu charla para ese día.

Quedo atento

Saludos.

**Comment by jeanmachuca** [comment]
Hola @L0rdKras !

Buenísimo! Ningún problema para el jueves 22. 

Nos vemos!

**Comment by rodrigoAdones** [comment]
Excelente, nos vemos el 22

Saludos
