### ISSUE TITLE
Manejo de estados con Context en React

### ISSUE THREAD

**Issue by daslaf** [Noders/Meetups#106]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Osman Cea

## ¿Cuál es el título de tu charla?
Manejo de estados con Context en React

## Danos una descripción de tu charla (20 palabras)
La charla trata sobre cómo separar el estado y la lógica de negocio de una aplicación de la capa de presentación usando Context en React.

## ¿Tienes alguna red social donde podamos contactarte?
https://twitter.com/daslaf

## ¿Representas a alguna compañía o empresa?
Cornershop (aunque no sé si voy directamente en representación... aunque supongo que sí)

## ¿Qué tipo de conector tiene tu notebook?

- [ ] HDMI
- [ ] Mini DisplayPort
- [ ] VGA
- [x] USB-C

## ¿Quieres agregar algo más?
Estoy muy entusiasmado por participar en Noders :)

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by rodrigoAdones** [comment]
Hola Osman

Muchas gracias por interesarte en dar la charla en el meetup de Noders.

Tenemos disponible espacio disponible para una keynote en el proximo meetup del 26 de Septiembre, te es posible presentarte ese día?

Quedamos atentos a tu confirmación.

Saludos.

**Comment by daslaf** [comment]
Sí Rodrigo, nos vemos el 26 entonces! ¿Hay algo con lo que les pueda ayudar o necesiten que lleve o algo por el estilo?

Saludos

**Comment by rodrigoAdones** [comment]
Genial Osman!!

No te preocupes por nada, nos vemos el jueves.

Saludos.

**Comment by daslaf** [comment]
Aprovecho de dejar el link a las slides:

https://docs.google.com/presentation/d/1DJQAfeDt0QhjUlMH3nsQfKn8RKfDg6G669dFdb3LXcI/edit?usp=sharing

Y al repositorio con el código del demo:

https://github.com/daslaf/state-management-react-context

Muchas gracias por el espacio y la buena onda <3

**Comment by rodrigoAdones** [comment]
Muchas gracias a ti Osman!!!

Fue genial tenerte como charlista. El tema es muy interesante y la comunidad lo disfruto mucho.

Esperamos volver a verte en el meetup

Gracias nuevamente.
