### ISSUE TITLE
Tendencias laborales tecnológicas

### ISSUE THREAD

**Issue by raicerk** [Noders/Meetups#108]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [ ] Keynote (20 a 30 minutos)
- [x] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Juan Mora

## ¿Cuál es el título de tu charla?
Tendencias laborales tecnológicas

## Danos una descripción de tu charla (20 palabras)
Se revisaran interesantes datos de tendencias tecnologías del país, así como tecnologías que las empresas requieren y como han evolucionado en el tiempo, ademas de presentar un proyecto de colaboración !

## ¿Tienes alguna red social donde podamos contactarte?
todas las redes sociales como @raicerk

## ¿Representas a alguna compañía o empresa?
Represento a una comunidad amiga @pgramadores

## ¿Qué tipo de conector tiene tu notebook?

- [x] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?
Espero que sea una gran experiencia el compartir estos geniales datos y este lindo proyecto que he impulsado :)

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by enBonnet** [comment]
Genial master, gracias por sumarte

**Comment by rodrigoAdones** [comment]
Hola @raicerk!!

Espero estes bien.

Quisiéramos saber si aun estas interesado en dar la lighting en el próximo meetup de la comunidad( tenemos como fecha tentativa el jueves 20 de febrero).

Ojalá pudieses presentar ese día, pero si no es posible podríamos coordinar para mas adelante, tu nos cuentas

Saludos.
