### ISSUE TITLE
Dynamic client-side PDF generation

### ISSUE THREAD

**Issue by betacar** [Noders/Meetups#11]
I want to talk about uBiome's use case of dynamic client-side PDF generation (our in-house reports microservice): reasons, approach taken, tools, challenges, pros and cons, and benefits for stakeholders.

The resources needed would be a video-beam or projector where I can show the slides, and internet connection.

**Comment by fforres** [comment]
Hey @betacar! 
How about next month? :smile_cat: 

We already have our 2 keynote speakers for this Meetup, but we'd love to schedule for the next one. 
(We are looking for lightning talks though)

**Comment by betacar** [comment]
@fforres I believe this can fit as a lighting talk.

**Comment by Xabadu** [comment]
@betacar awesome!, let's do it then. Do you need anything from us?

**Comment by fforres** [comment]
Awesome! 
Lightning next week then :+1:

**Comment by betacar** [comment]
@fforres @Xabadu Lighting talk will be!

How much time should be? I'll only need a projector.

Maybe a Jet, and a Llama, and a Jet for my Llama. But that's optional. :P

**Comment by Xabadu** [comment]
One Llama on the way! See you thursday!

**Comment by Xabadu** [comment]
@betacar can you provide us a link to your slides so we can add them to the repo please? Thanks!
