### ISSUE TITLE
Al infinito y más allá con websocket

### ISSUE THREAD

**Issue by Pillin** [Noders/Meetups#110]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [X] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Pillippa Pérez Pons

## ¿Cuál es el título de tu charla?
 Al infinito y más allá con websocket

## Danos una descripción de tu charla (20 palabras)

Qué es?, Qué se necesita? Cómo se implementa? Ejemplos y comparativa entre algunas de las librería que lo implementan

## ¿Tienes alguna red social donde podamos contactarte?

Github: https://github.com/Pillin
Twitter: https://twitter.com/_pilliin_

## ¿Representas a alguna compañía o empresa?
No
## ¿Qué tipo de conector tiene tu notebook?

- [X] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?
=)

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by rodrigoAdones** [comment]
Hola Pillippa!!

Muchas gracias por interesarte en hacer una presentación en el meetup de Noders =)

Te cuento que nuestro proximo meetup ser el 14 de noviembre (aun estamos confirmando el lugar), te gustaría presentar ese día? nos confirmas por favor.

Que estes bien, y gracias nuevamente

Saludos.

**Comment by Pillin** [comment]
Hola Rodrigo!!

Muchas gracias por la oportunidad y me parece genial la fecha! :D. Así que confirmo.
Qué tengas un excelente día.

Saludos.

**Comment by Pillin** [comment]
Hola Rodrigo

Qué tal?, oye, podría quedar para el siguiente evento (Dic)?

Gracias! Saludos

**Comment by rodrigoAdones** [comment]
Hola Pillippa

No hay problema, te dejamos anotada para el meetup de diciembre

Saludos

**Comment by rodrigoAdones** [comment]
Hola @Pillin!! 

Paso harto tiempo... espero estes bien.

Queríamos saber si aun estas interesada en dar una charla en el meetup

Estamos organizando uno para este mes( el 20 es nuestra fecha tentativa)

Nos gustaría mucho que pudieses presentarte ese día... o si no anotarte para otro meetup, tu nos cuentas que te parece.

Saludos!

**Comment by Pillin** [comment]
hola @rodrigoAdones 

Gracias, también espero que estés muy bien.

Lamentablemente, voy a desistir. En otra ocasión =).

Saludos!

**Comment by rodrigoAdones** [comment]
Ok @Pillin sera en otra ocasión

Quedo con la duda... dejamos abierto esta keynote y te puedo seguir contactando? o quieres abrir otro mas adelante con un nuevo tema?

Saludos.

**Comment by Pillin** [comment]
@rodrigoAdones Mejor cerrarlo 
Saludos

**Comment by rodrigoAdones** [comment]
Ok @Pillin 

Gracias una vez mas, ojalá puedas acompañarnos en un proximo meetup con una charla

Saludos, que estes bien
