### ISSUE TITLE
Programación funcional 101 en JavaScript

### ISSUE THREAD

**Issue by daslaf** [Noders/Meetups#111]
## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Osman Cea

## ¿Cuál es el título de tu charla?
Programación funcional 101 en JavaScript

## Danos una descripción de tu charla (20 palabras)
Esta charla es una introducción a conceptos de programación funcional en Js (high order functions, currying, aplicación parcial, etc...)

## ¿Tienes alguna red social donde podamos contactarte?
https://twitter.com/daslaf

## ¿Representas a alguna compañía o empresa?
Cornershop

## ¿Qué tipo de conector tiene tu notebook?

- [ ] HDMI
- [ ] Mini DisplayPort
- [ ] VGA
- [x] usb-c

## ¿Quieres agregar algo más?
Pizza con tequeños

**Comment by rodrigoAdones** [comment]
Hola @daslaf!!

Espero estes bien

Gracias por interesarte en dar una charla en el meetup de Noders

Crees poder presentar el jueves 20 de Febrero? Quedamos atentos para confirmar.

Saludos

**Comment by daslaf** [comment]
Hola @rodrigoAdones

Sí, no hay problema para el Jueves 20. Saludos.

**Comment by rodrigoAdones** [comment]
Genial @daslaf!!

Muchas gracias, pronto empezaremos la promoción del evento

Saludos.

**Comment by daslaf** [comment]
Dejo las slides de la presentación. Saludos

https://docs.google.com/presentation/d/1Igoub1e9lq22Jho4hCOcDgtzjmw1gxvLMXevol_1BIQ/edit?usp=sharing

**Comment by rodrigoAdones** [comment]
Gracias por compartir las slides @daslaf!!

Un honor haberte tenido nuevamente dando una charla en el meetup, estuvo muy interesante.

Saludos.
