### ISSUE TITLE
Introducción a ZeroMQ con Node.js / Keynote

### ISSUE THREAD

**Issue by camilochs** [Noders/Meetups#12]
Nombre del charlista: Camilo Chacón Sartori

Contacto: www.camilochacon.com

Nombre de la charla: Introducción a ZeroMQ con Node.js: Para construir sistemas distribuidos de mensajería.

Descripción de la charla: Primero responderemos que es ZeroMQ(Zero em Queue), para que se utiliza y como podemos integrarlo con Node.js. ZeroMQ nos permite crear fácilmente patrones de arquitectura para nuestras aplicaciones distribuidas.

También mencionare como hemos utilizado esta tecnología en mi trabajo, que es una empresa del rubro minero, donde las comunicaciones son un constante problema.

Camilo Chacón Sartori

**Comment by Xabadu** [comment]
Hola @camilochs. Buenísima, quedas confirmado para el próximo Meetup.

Recuerda que la charla tiene un máximo de 20 mins y que será grabada, así como los slides subidos a este repositorio, por lo que debes evitar incluir información sensible que no pueda ser compartida.

¿Necesitas algo de nuestra parte?

Saludos!

**Comment by camilochs** [comment]
Hola!, por ahora no. Es la primera vez que iré por lo tanto estoy motivado :)

**Comment by Xabadu** [comment]
Buenísima. Si necesitas algo, no dudes en avisarnos.

Saludos!

**Comment by fforres** [comment]
Genial @camilochs, y felicitaciones!

Solo una pequeña consulta. 
Algún chance de que grabes tu pantalla durante la presentación? 

(Puedes usar camstudio si usas windows o quicktime si usas mac.
https://github.com/JavascriptChile/Meetups/issues/10)

Si necesitas cualquier cosa de nosotros, no dudes en consultarnos.
Quedamos al habla!

**Comment by camilochs** [comment]
Si claro, aveces debo grabar con quicktime :) 
Saludos

**Comment by Xabadu** [comment]
Hola @camilochs. Haremos un cambio de venue para este evento, será en las oficinas de Mercado Libre (Apoquindo 4820, Torre 2, Piso 21, Las Condes). Disculpa por el aviso tan encima. Avísanos si te complica en algo.

Saludos!

**Comment by camilochs** [comment]
@Xabadu  Hola, no te preocupes :), de hecho ya había visto el cambio de lugar del evento 👍 
Saludos!

**Comment by Xabadu** [comment]
Gracias por la charla @camilochs. Buen material, lo subiremos pronto.

Saludos!
