### ISSUE TITLE
Propuesta de Charla

### ISSUE THREAD

**Issue by alexberrocal** [Noders/Meetups#13]
Nombre del charlista: Jorge Garcés

Contacto: https://www.facebook.com/garcescarrasco

Nombre de la charla: Creación de Bots para Messenger Facebook y Telegram

Descripción de la charla: Se explicará como crear bots en node js para Facebook messenger y Telegram. Ejemplos buscar indicadores Chile en Facebook (https://www.facebook.com/indicadoresChile) y en Telegram IndicadoresChile

**Comment by fforres** [comment]
Hola @alexberrocal 
Suena genial la charla! 

Quieres hacer algo como un workshop? o solamente una charla? 

Aprovecho de contarte, las charlas son de 25 minutos +- (Con un tiempo de preguntas al final)

**Comment by alexberrocal** [comment]
Hola  @fforres 

Seria una charla pero mostraremos una demo de como crear un bot para ambas plataformas desde 0.
Si! trataremos de acotarlas a 25 minutos.
Gracias!

Saludos

**Comment by lporras** [comment]
Hola @alexberrocal 

Estarías dispuesto para dar tu charla en el próximo [meetup](http://www.meetup.com/Javascript-Chile/events/231001805/) ?

saludos,

Luis Porras

**Comment by lporras** [comment]
Hola @alexberrocal 

Estarías dispuesto a realizar la charla para el próximo [meetup](http://www.meetup.com/Javascript-Chile/events/231001805/)?

Estamos programándolo para el 7 de Julio como fecha tentativa.  Te sirve esa fecha?

Saludos

**Comment by alexberrocal** [comment]
Hola @lporras 

Si, puedo prensentar en el próximo meetup.

Saludos

**Comment by fforres** [comment]
Nice!
Entonces, @alexberrocal solo para confirmar... solo charla, no?

Btw, te molesta que grabemos tu presentación?

**Comment by alexberrocal** [comment]
si, solo charla
Ningún problema de la grabación.
Entonces seria para el 7 de Julio?

**Comment by lporras** [comment]
Hola @alexberrocal te vamos a agregar a la descripción del meetup, será el 7 de Julio en las oficinas de Mercado Libre, puedes ver la info acá: [meetup](http://www.meetup.com/Javascript-Chile/events/231001805/)

Nos vemos allá!

**Comment by alexberrocal** [comment]
Hola @lporras 
Perfecto, 
gracias nos vemos ese día.
Saludos
