### ISSUE TITLE
Propuesta de Charla

### ISSUE THREAD

**Issue by tomascharad** [Noders/Meetups#14]
Nombre del charlista: Tomás Charad

Contacto: https://github.com/tomascharad/

Nombre de la charla: Model environment, cómo establecer relaciones en el frontend.

Descripción de la charla: Explica como hacer funcionar relaciones en el frontend cuando usamos api's normalizadas.

**Comment by lporras** [comment]
Hola @tomascharad,

Muchas gracias por postular para una charla, suena muy interesante tu tema, me tomé la libertad de buscar sobre model environment y me di cuenta que es el nombre de una librería en Node.js de tu autoría, impresionante!

Consulta, de cúanto tiempo puede ser tu charla? 5 - 10 - 15 min?

Por otro lado, para el meetup de Julio ya tenemos a los charlistas, entonces tendría que ser para el meetup de Agosto, estarías disponible?

**Comment by tomascharad** [comment]
Hola @lporras,

No tendría problema de hacerlo en Agosto. Cuál sería la fecha para agendarlo?
Esta va a ser la primera vez que presente un trabajo propio... Cuál es el tiempo máximo para la presentación?
Muchas gracias.

**Comment by tomascharad** [comment]
Hola @lporras,

Acabo de actualizar el readme del proyecto. Ha habido harta gente interesada en la comunidad de redux, creo que alguien quiere incluso hacer una mención del proyecto.

Dejo acá mi conversación con él.

tomascharad-Today at 11:37 PM
Hi guys
I'm working on a project that is meant to recreate relationships on the client side using normalized api's
https://www.npmjs.com/package/model-environment
npm
model-environment
Creates an environment that permits to define relations between objects when receiving data from normalized Api's
If you have some feedback I would be very pleased to hear from you

acemarke-Today at 11:38 PM
sure.  first question, and I think I asked this the other day and not sure if you saw it: how does this differ from https://github.com/tommikaikkonen/redux-orm ?
GitHub
tommikaikkonen/redux-orm
redux-orm - A small, simple and immutable ORM to manage relational data in your Redux store.
￼
tomascharad-Today at 11:39 PM
Is already in the docs
The main difference is that model-environment is not coupled to redux

acemarke-Today at 11:40 PM
technically, neither is redux-orm

tomascharad-Today at 11:40 PM
By using model-environment you can update your state as you would do naturally with redux
Really? But in the docs they show a different way to update the state

acemarke-Today at 11:41 PM
if you look at redux-orm's package.json, the only dependencies are babel-runtime, immutable-ops, reselect, and lodash
it does provide a way to generate a top-level reducer function you can hook into your redux store
but other than that, it just deals with plain data
in my own app, I'm not even using the built-in reducer function.  I'm just using it as a sort of advanced selector layer, and immutable update layer within my own reducer functions
(obviously pretty familiar with it, which is why my first question is how they compare)

tomascharad-Today at 11:43 PM
Ok, I may have misunderstood the docs
The other difference is that we use name conventions
And the library is meant to be used with normalized api's
Actually we made it thinking about how to recreate relations after 'destroying them' after using normalized api's

acemarke-Today at 11:45 PM
so your lib assumes the data is already showing up on the client in normalized form?

tomascharad-Today at 11:47 PM
Yes, but that doesnt mean that you couldn't use normalizr

acemarke-Today at 11:48 PM
a couple other differences I'm seeing: Redux-ORM is noticeably bigger (about 2000 lines rather than 150), but it also does a lot of work to define ES5 properties on your model instances for each relation and each plain data field(editado)
and has a bunch of logic for filtering and querying items

tomascharad-Today at 11:49 PM
Yes my lib is very small

acemarke-Today at 11:49 PM
which is certainly a useful attribute

tomascharad-Today at 11:49 PM
I know that working on querying nd filtering functionalitites is the next step
Thanks

acemarke-Today at 11:50 PM
I've bookmarked your lib and will glance at it further later. I'll also probably add it to my Redux addons list at https://github.com/markerikson/redux-ecosystem-links
GitHub
markerikson/redux-ecosystem-links
redux-ecosystem-links - A categorized list of Redux-related addons, libraries, and utilities
￼
tomascharad-Today at 11:50 PM
Many thank @acemarke !
If you have any other feedback just let me know
I'm very entusiastic about this project
My mail is tomas@tcit.cl

**Comment by lporras** [comment]
Hola @tomascharad,

El próximo meetup será el 4 de Agosto, como fecha tentativa, ya que procuramos realizarlo los primeros jueves de cada mes, y en el mismo venue, el cual es el HQ de Mercado Libre Chile.

Y respecto a la duración de tu charla, yo opino que podrías hacerla como una charla corta de 5min, donde presentes el caso de uso de tu librería, los motivos que te llevaron a crearla y un pequeño demo, donde puedas explicar el uso de la librería.

Como tip para armar tu presentación te puedo recomendar utilizar slides.com o usar Reveal.js para armar tus diapositivas, luego puedes crear un repo en github con el código de tu presentación, lo que te permitirá publicar tus slides en  [gitHub pages](https://pages.github.com/).

P.D: Que genial que haya interesados en probar tu librería!
P.D 2: Te invito a que entre al slack de la comunidad [Noders](http://noders.cl/#!/), uno de sus canales es para hablar de React.js

**Comment by tomascharad** [comment]
Hola @lporras ,

Ok, gracias por tus recomendaciones.
Podría mi charla durar un poco más? Lo que pasa es que quiero darle una vuelta un poco a todo el concepto de api's normalizadas y porque me parece bueno implementarlas.
Hay bastantes cosas que podría hablar sobre esto, no solo en la libraría en si misma.

**Comment by lporras** [comment]
@tomascharad si claro, te parece entonces 10 minutos?

**Comment by tomascharad** [comment]
Perfecto @lporras, muchas gracias.
Una pregunta, la presentación es en español o inglés?
Estaba pensando que si puede ser en inglés podría poner esta presentación como parte de la documentación de la librería.

**Comment by lporras** [comment]
@tomascharad te refieres a los slides cierto? pues no le veo problema a que estén en inglés, así gente que habla inglés puede entender algo tu charla aún cuando no te entiendan el español.

**Comment by tomascharad** [comment]
Les dejo a todos la referencia para las diapos de la presentación: https://goo.gl/2McFJT
