### ISSUE TITLE
Propuesta de Charla Webpack

### ISSUE THREAD

**Issue by elsilentforce** [Noders/Meetups#15]
Saludos!
Quisiera proponer una charla sobre Webpack, la idea es darlo a conocer para los que aún no lo utilizan y ayudar un poco a los que han sufrido configurandolo.

La idea es explicar en 15 minutos de qué se trata, generando un pequeño ambiente de desarrollo para aplicaciones con React.

Eso!

Quedo atento a sus comentarios (:

**Comment by pamo** [comment]
Estuviera bueno un taller, no? Quizás ir por unos pasos sobre como convertir una configuración de Grunt/Gulp a Webpack. Como se transforma ES6, CSS, etc.

**Comment by elsilentforce** [comment]
Saludos @pamo!
Si, también podría ser un taller cortito de cómo configurar webpack para generar un dev environment.
Si me lo permiten los organizadores no tendría problemas en hacerlo.

**Comment by fforres** [comment]
@elsilentforce
Me suena genial el tema, bastante interesante, mucha gente (Sorry la demora en contestar) 

Tienes pensado algun tiempo o formato para la charla? 5 - 10 - 20 min?

**Comment by lporras** [comment]
@elsilentforce gracias por tu propuesta, nos interesa mucho el tema, @fforres Patricio indicó que su charla sería de 15 minutos.

Te confirmamos que estás seleccionado para el meetup de Agosto, tenemos como fecha tentativa el 4 de Agosto en las oficinas de Mercado Libre.  Te estaremos informando.

saludos!

**Comment by fforres** [comment]
Me gustó la idea @pamo 
Eso daría para un taller con bastante pelea eso si, `Grunt/Gulp vs Webpack` últimamemente es el `tab vs spaces` de los building tools 😁 

Podríamos organizar algo off-meetup, para hacer ese taller, alguien se la juega con darlo?

**Comment by fforres** [comment]
Burp... brain fart right there. 

Genial, se imprime entonces! 

Te molesta si grabamos el meetup @elsilentforce ?

**Comment by elsilentforce** [comment]
@lporras Perfecto! Prepararé material para ése día.

@fforres No me molesta, la idea es que menos gente sufra tratando de utilizar WebPack (:

**Comment by fforres** [comment]
Awesome @elsilentforce :)
