### ISSUE TITLE
Propuesta de Charla: Desarrollo de Videojuegos con React Native

### ISSUE THREAD

**Issue by Xabadu** [Noders/Meetups#16]
Nombre del charlista: Fernando Larrañaga

Contacto: https://github.com/xabadu/

Nombre de la charla: Desarrollo de Videojuegos con React Native.

Descripción de la charla: Dar a conocer porque React Native, en base a sus características claves, se puede perfilar como una plataforma atractiva para el desarrollo de videojuegos móviles, tanto por su ecosistema de apoyo actual como por lo que viene a futuro.

**Comment by lporras** [comment]
Muchas gracias @Xabadu por la propuesta, suena muy interesante el tema, pregunta: cúanto tiempo duraría tu charla? 5min - 10min - 15min?, lo otro, estás disponible para el 4 de Agosto?

saludos!

**Comment by Xabadu** [comment]
Cerraré por ahora, because life and reasons, pero reabriré más adelante.
