### ISSUE TITLE
Propuesta de Lightning Talk

### ISSUE THREAD

**Issue by pankas87** [Noders/Meetups#17]
Nombre del Charlista: Leonardo Graterol
Contacto: leonardo@marketrealist.com / 9 87677476
Nombre de la charla: Propuesta laboral Market Realist
Descripción de la Charla: Lightning talk mostrando la oferta laboral de Market Realist, empresa basada en NYC, que está buscando un desarrollador remoto en Santiago

**Comment by lporras** [comment]
Hola Leonardo,

Muchas gracias por postular a una lightning Talk, te anotaremos en el track,
saludos!

Luis Porras
