### ISSUE TITLE
Keynote: 4 años desarrollando NodeJS.

### ISSUE THREAD

**Issue by csepulveda** [Noders/Meetups#18]
Queremos contar la experiencia de desarrollar un gran proyecto utilizando NodeJS, siendo nuestro primer Commit para este proyecto en Septiembre de 2012, comenzando con node 0.8 y express 2.5. Actualmente tenemos más de 9mil commits en este proyecto en particular, siendo el 79% de nuestro proyecto CoffeeScript y 9% javascript.

Este proyecto en particular es el backend de todo el contenido de VOD y Live Streaming de MEGA, CDF, TVN y otros grandes medios fuera de chile (Colombia, Mexico, USA, Brasil).

Creo nuestra experiencia, principalmente los errores encontrados y arreglados en el camino puede ayudar mucho a quienes quieran comenzar con grandes proyectos en NodeJS.

**Comment by fforres** [comment]
Hola @csepulveda !!! 
Se lee genial la charla, vamos a actualizar el sitio del meetup ahora :) 

Las keynotes están pensadas para 20/30 minutos + preguntas aparte. Saludos!
