### ISSUE TITLE
Propuesta de Charla

### ISSUE THREAD

**Issue by carlosrojaso** [Noders/Meetups#2]
Nombre del charlista: Sebastian Gomez

Contacto: twitter.com/sebasagar

Nombre de la charla: Creación de una aplicación tipo reddit en Angular 2.0.

Descripción de la charla: Mostraremos el funcionamiento de una aplicación tipo reddit usando web components y algunos conceptos de Angular 2.0

Sebastian Gomez
Magister en ingeniería de sistemas e informática.
Desarrollador Web y Móvil desde 2008
Apasionado por la web y el desarrollo móvil.
Si lo puedes medir lo puedes mejorar.
CTO de Sponzor.ME

**Comment by Xabadu** [comment]
Hola @carlosrojaso 

Buenísima. Gracias por postular una charla. 

¿Será presencial o remota?

Recuerden que deben grabar su pantalla para que después podamos compartir el video junto con la presentación. Si necesitan ayuda con esto, no dudes en avisarnos.

**Comment by carlosrojaso** [comment]
Presencial :)
ᐧ

Un Abrazo / Kind Regards / Atenciosamente,

Ing. Carlos A. Rojas.
Tel: (+1) 5104176510
Tel: (+57) 3162914133
@carlosrojas_o

2015-12-09 13:16 GMT-03:00 Fernando Larrañaga notifications@github.com:

**Comment by Xabadu** [comment]
Confirmada.

Mantendremos el issue abierto por si alguien quiere aportar/preguntar algo.

Saludos!
