### ISSUE TITLE
Propuesta Lightning Talks: Variables de entorno en AngularJS

### ISSUE THREAD

**Issue by jacobparra** [Noders/Meetups#20]
Nombre del charlista: Jacob Parra

Contacto: https://github.com/jacobparra/

Nombre de la charla: Variables de entorno en AngularJS.

Descripción de la charla: Como manejar las variables de configuración de una webapp en AngularJS y mantenerlas separadas del código fuente.

**Comment by jacobparra** [comment]
Hola! Es para saber si habrá espacio para el próximo meetup.

/cc @Xabadu @fforres

**Comment by fforres** [comment]
Hola @jacobparra! 
Por mi me parece genial, te agregamos al correo de update del meetup entonces!
