### ISSUE TITLE
(🔑📝) Keynote: Iniciando la vida con Loopback.

### ISSUE THREAD

**Issue by JonDotsoy** [Noders/Meetups#22]
En esta keynote, poder hablar un poco como usar [loopback](https://loopback.io/) los primeros días no fallar en el intento ⚰.
- Entendiendo su  estructura.
- Entendiendo la herramienta de strongloop.
- Cómo usar loopback en producción.

**Comment by Xabadu** [comment]
Hola @JonDotsoy, me parece excelente. ¿Te animas a hacerla en el meetup de la próxima semana?

Saludos!

**Comment by JonDotsoy** [comment]
😄 : Of course! No hay problema.

**Comment by Xabadu** [comment]
Excelente! Quedaste confirmado entonces. Acá está la info del evento: https://www.meetup.com/es-ES/Javascript-Chile/events/233102729/

Si tienes dudas o necesitas algo de parte de nosotros, no dudes en avisarnos.
