### ISSUE TITLE
Progressive web apps

### ISSUE THREAD

**Issue by tomascharad** [Noders/Meetups#23]
Hola,

Me gustaría poder compartir mi experiencia con esta tecnología.
En concreto realizamos un proyecto para CONAF usando PWAs y me gustaría hablar un poco sobre esto.
Creo que es un tema bien interesante y tengo harto para compartir, sobre todo la integración con Webpack, react, etc...
Un abrazo.

**Comment by Xabadu** [comment]
Hola @tomascharad,

Perfecto! Suena bien. Nos queda un cupo libre de charlas para la próxima semana. ¿Te sumamos ahí?

Saludos!

**Comment by tomascharad** [comment]
Hola @Xabadu ,

Justo este miércoles tengo visita a terreno fuera de Santiago, pero feliz de dejarlo para el próximo mes! Si llegan a cambiar el día al Jueves o Viernes podría sin ningún problema.
Un abrazo!

**Comment by Xabadu** [comment]
@tomascharad si, te dejamos confirmado para Diciembre. El venue está medio complicado para otro día este mes, así que tiene que ser el miércoles.

Coordinamos nuevamente cerca de la fecha. Gracias por sumarte!

**Comment by Xabadu** [comment]
Hola @tomascharad, estamos confirmando las charlas para el meetup de este jueves. ¿Sigue en pie la tuya? Saludos!

**Comment by tomascharad** [comment]
Hola @Xabadu,

Me siento un poco avergonzado de decir esto pero me volvió a pillar el mes y el día me juega en contra. Podremos dejar la charla para el próximo mes si es posible?

Si esto complica mucho su gestión dime para ver si lo puedo solucionar de otra forma.

Un abrazo.

**Comment by Xabadu** [comment]
@tomascharad dale, no hay problema, veámoslo para el próximo mes.

Abrazo!

**Comment by tomascharad** [comment]
Hola! Hay algo en lo que pueda ayudar?
