### ISSUE TITLE
Propuesta Charla: Conoce StealJS

### ISSUE THREAD

**Issue by m-mujica** [Noders/Meetups#24]
| - | - |
|---|---|
| Expositor  | Manuel Mujica   |
| Url  | https://twitter.com/m_mujica   |
| Nombre de la charla  |  Conoce StealJS |
| Descripción  | StealJS es una librería para cargar dependencias y crear bundles con los                                              assets que tu aplicación necesita para correr en un browser de forma eficiente. Funciona con ES6, CommonJS, AMD, CSS, LESS y más.  |

**Comment by Xabadu** [comment]
Hola @m-mujica, gracias por sumarte. ¿Te confirmamos para el Meetup de este jueves? Saludos!

**Comment by m-mujica** [comment]
@Xabadu vale, perfecto!

**Comment by Xabadu** [comment]
@m-mujica perfecto, confirmado! Recuerda que es en las oficinas de MercadoLibre. Acá está toda la información del evento: https://www.meetup.com/es-ES/Javascript-Chile/events/234590771/

Avísanos si necesitas algo de nuestra parte. Nos vemos!
