### ISSUE TITLE
Devops para NodeJS apps

### ISSUE THREAD

**Issue by feranto** [Noders/Meetups#25]
Como diseñar un proceso de devops con las siguientes prácticas:

- Continous Integration
-Release Management
-Continous Deployment

Para apps en NodeJS usando vsts.

**Comment by Xabadu** [comment]
Hola @feranto, buenísima. El próximo Meetup es mañana y nos queda un cupo para charlas, ¿alcanzas, o para el próximo mes? Saludos!

**Comment by JonDotsoy** [comment]
Vamos @feranto se ve interesante 👍

**Comment by feranto** [comment]
saludos @Xabadu será para el próximo mes estimado, please confirmar cupo? Estuvo muy buena hoy día, gracias!

**Comment by Xabadu** [comment]
Listo @feranto, confirmado para el Meetup de Enero. Avísanos si necesitas algo!

**Comment by fforres** [comment]
Oiga don @feranto!!!
Tienes un correo para contactarte? :)

**Comment by feranto** [comment]
@fforres hasta ahora lo veo, puedes contactarme a ferant0@outlook.com. A la orden!
