### ISSUE TITLE
Propuesta de Charla

### ISSUE THREAD

**Issue by DMasterIO** [Noders/Meetups#26]
Nombre del charlista: César Encina

Contacto: @dmaster69

Nombre de la charla: Deployando Lambda con ClaudiaJS

Descripción de la charla: Lambda se ha convertido en uno de los servicios más utilizados por su funcionalidad y costo, pero el subir, versionar y gestionar las distintas funciones de forma manual es un caos. Por eso presentaré como ClaudiaJS ayuda en esta etapa.

**Comment by Xabadu** [comment]
Listo @DMaster69 confirmado para el Meetup de Enero. Avísanos si necesitas algo!
