### ISSUE TITLE
Donejs con feathersjs: lo básico 

### ISSUE THREAD

**Issue by nriesco** [Noders/Meetups#27]
Lo básico de ocupar donejs (https://donejs.com/) junto con un API server en feathersjs (http://feathersjs.com/).

_Temas:_
- **Motivación**: MVC, MVvC, historia personal
- **Feathers básico**: crear server y crear servicios / modelos en mongoose
- **Donejs básico**: componente con conexión a API
- **Donejs intermedio**
  - CRUD
  - mejoras en interfaz / usabilidad

_Dependiendo del tiempo:_
- **Feathers intermedio**: 
  - crear un servicio sin base de datos
  - hooks básicos 
- **Tests de interfaz en donejs**

**Comment by fforres** [comment]
Genial master! 
Las charlas normalmente son de 30 a 35 minutos, (Pero pueden extenderse algunos con preguntas)
Cabe dentro del tiempo? 👍 

(Also, te dejé un mensaje en el chat de meetup.com)

**Comment by fforres** [comment]
Also, te dejé un mensaje en interno

**Comment by nriesco** [comment]
@fforres la idea es hacerlo en ese tiempo, ahora si hay interés, tiempo y ganas no hay problema en extenderse por mi parte, creo que el tema da para largo. De todas formas esto es algo introductorio solamente, no soy el gurú de feathers ni de donejs pero creo que puedo compartirles lo que he ido aprendiendo el último tiempo pues es realmente valioso.

**Comment by fforres** [comment]
Awesome!
