### ISSUE TITLE
Lightning talk: Ejemplo de Telegram bot con nodejs

### ISSUE THREAD

**Issue by juanpabloaj** [Noders/Meetups#29]
Una lightning talk sobre como hacer un bot para telegram con nodejs

Voy a explicar como hice 

https://github.com/juanpabloaj/fromcommandlinebot

Un bot para enviar mensajes desde la linea de comandos a telegram

y como lo tengo alojado en https://zeit.co/now

**Comment by fforres** [comment]
👍  Para hoy? 
Estaría awesome!!  @juanpabloaj !! :D

**Comment by juanpabloaj** [comment]
@fforres si, para hoy. no voy a preparar nada muy complejo, solo describir como funciona y que cosas se utilizan.

**Comment by fforres** [comment]
Genial!! 
Se agrega 👍

**Comment by juanpabloaj** [comment]
la presentación 

http://platon.io/gist/527f4b6dc3d7f0f900686342086bde0b
