### ISSUE TITLE
Event-driven Code with Node.js in AWS Lambda

### ISSUE THREAD

**Issue by jpizarrom** [Noders/Meetups#3]
Nombre del charlista: Juan Pizarro

Contacto: twitter.com/jpizarrom

Nombre de la charla:  Event-driven Code with Node.js in AWS Lambda

Descripción de la charla: Mostraré una implementación de notificaciones de nuevas licitaciones usando datos de la api de mercado publico con AWS Lambda + Amazon DynamoDB + Amazon Kinesis + Amazon SNS

Lead Software Engineer @ admetricks.com

**Comment by fforres** [comment]
Se ve genial @jpizarrom !

Sería cool enfocarla también a los problemas que tuviste y como los solucionaste, más que solo código :) 

Solemos subir las presentaciones a internet, para que no muestres nada que sea información sensible :+1: 

Para cuanto tiempo tienes considerada la presentación?

**Comment by jpizarrom** [comment]
20-25min

**Comment by fforres** [comment]
Awesome! :+1:

**Comment by luchosrock** [comment]
:+1:  :smile:

**Comment by jpizarrom** [comment]
@fforres me agendaron una reunion el jueves en el horario de meetup, por lo que no podré asistir, disculpen

**Comment by Xabadu** [comment]
Ok. Gracias por avisar.

**Comment by DMasterIO** [comment]
@fforres @Xabadu si se les baja alguien o necesitan a alguien, puedo dar una lighting similar a esta, contexto totalmente diferente pero tecnologías similares, una galería de imágenes con AWS Lambda + AWS S3 + Firebase + un poco de Angular y el sitio montado en githubpages, ahorrándose el backend :P

**Comment by fforres** [comment]
Buenisima :D @DMaster69 
Me gusta bastante, no han/has pensado hacer un tutorial/workshop? 
:+1: 
Podríamos abrir otro issue para esto si

**Comment by DMasterIO** [comment]
@fforres acabo de ver la respuesta, ya no alcanzo a preparar nada, pero abriré otro issue para el próximo meetup :+1:

**Comment by jpizarrom** [comment]
Hola, puedo hacer esta charla el jueves si aún quedan cupos.

Saludos

**Comment by Xabadu** [comment]
Hola @jpizarrom, buenísima! Nos queda un cupo abierto para este Jueves, así que felices de tener la charla ahí.

¿Necesitas algo de nuestra parte?

Saludos!
