### ISSUE TITLE
Charla: Electronjs y el futuro de las aplicaciones de escritorio

### ISSUE THREAD

**Issue by DracotMolver** [Noders/Meetups#31]
Me gustaría poder dar una pequeña introducción al framework ElectronJS y dejar como planteamiento el futuro de las aplicaciones de escritorio. Todo esto bajo mi experiencia al desarrollar una aplicación usando ElectronJS. La aplicación, Soube, actualmente se encuentra en mi Dashboard y desde el momento de subirla a las App realizadas con ElectronJS he tenido una gran acogida desde distintos lugares y personas.

**Comment by fforres** [comment]
Holas @DracotMolver .
Buenísima, para cuantos minutos estás considerando la presentación?
Lightning? Keynote?

**Comment by DracotMolver** [comment]
@fforres genial :). Sería un Keynote solo sobre ElectronJS, yo creo que sería de 25 min. Sería genial para abril, así tengo tiempo para preparar una presentación con algunos ejemplos de códigos :), o para la fecha que estimes conveniente. Es mi primera vez participando en ésto y encuentro genial que exista esta comunidad 👍 y dar la instancia para compartir conocimientos en las charlas.

**Comment by fforres** [comment]
Para cuando quieras.
Genial, te dejo anotado para abril entonces @DracotMolver

**Comment by DracotMolver** [comment]
@fforres Sí, genial :). Nos vemos en abril. Gracias :)

**Comment by fforres** [comment]
Holas @DracotMolver !!
como va?

Quería confirmar si aun va tu charla para Abril. Estamos planeando una charla el jueves 6 en las oficinas de Globant (Cerca del metro manquehue)

Still in??

**Comment by DracotMolver** [comment]
Hola @fforres , Sí va, estoy armando la presentación :). Dale bkn, no hay problemas con el lugar

**Comment by fforres** [comment]
Awesome, mandamos el update entonces :)

**Comment by DracotMolver** [comment]
Sería un keynote. Daré un introducción del por qué del título, como surge ElectronJS, algunas aplicaciones desarrolladas usando este framework y la explicación de su arquitectura. Necesitas que te envíe la prensentación?, estoy usando RevealJS, así que se puede visualizar en cualquier navegador

**Comment by DracotMolver** [comment]
@fforres debo informar que no podré asistir y dar la charla, acabo de emoezar a trabajar en un lugar nuevo y el horario, junto con la distancia, no me acompañan. Esto era algo que no había previsto para este mes, pero salió antes de tiempo el trabajo. Mis disculpas si esto genera algún inconveniente

**Comment by fforres** [comment]
@DracotMolver 
Que mala onda, estamos viendo como lo solucionamos.
Te contesté tu correo, habrás tenido tiempo de verlo??

**Comment by DracotMolver** [comment]
Hola Felipe, lo estaba leyendo ahora. Lo veo súper difícil. Ahora trabajo
en Maipú. Trabajé dos años en Alonso de Córdova con Cerro colorado y es un
viaje de casi dos horas. Ahora tengo horario y salgo a las 6. De nuevo, mil
disculpas, estaba realmente entusiasmado, pero tengo prioridades más
importantes. Saludos
