### ISSUE TITLE
aureliajs

### ISSUE THREAD

**Issue by ormasoftchile** [Noders/Meetups#33]
Hola!!!

Me avisaron de este espacio y puedo aportar con una charla que ya he hecho sobre aureliajs.
Es un framework para desarrollo de aplicaciones con esnext, two way databinding, y su principal enfoque es el apego a estándares y evitar abstracciones innecesarias.

Tengo una keynote.

Avísenme por favor si les interesa para programarme.

Saludos!!!

Cristián Ormazábal

**Comment by fforres** [comment]
Genial! @ormasoftchile 
Para abril ya tenemos listo el cupo de las keynotes, podría ser para Mayo??

**Comment by ormasoftchile** [comment]
Por supuesto. Indícame la fecha para programar. Saludos

**Comment by luchosrock** [comment]
@ormasoftchile tenemos un cupo para dar charla el próximo 11 de mayo

**Comment by ormasoftchile** [comment]
súper. por favor escríbeme al correo para contactarnos.

Saludos.
