### ISSUE TITLE
Presentación de Weasel

### ISSUE THREAD

**Issue by peterlavey** [Noders/Meetups#34]
Es una aplicación web para mockear servicios con un nuevo concepto de agrupación de datos.

**Comment by DMasterIO** [comment]
Excelente @peterlavey!!
Te interesa exponer el meetup de la próxima semana?? 
Además podrías darnos una breve descripción de la charla y el tiempo que necesitas para esta.
¿Necesitas algo adicional / especial para la presentación?

**Comment by luchosrock** [comment]
Sería entonces una charla de 15 minutos aproximadamente. El título es "Weasel: mock de servicios rest para dejar de preocuparse por el backend" ??? opiniones? :smile:

**Comment by peterlavey** [comment]
Sí, 15 minutos aprox, un proyector si es posible para presentarlo desde  mi note.
