### ISSUE TITLE
Presentacion: React Native Animations

### ISSUE THREAD

**Issue by johuder33** [Noders/Meetups#35]
Presentación para dar a conocer como se puede trabajar con Animations en React Native, me parece interesante ya que me parece que no ha habido una charla de este tipo y me parece también que React Native ha generado una gran comunidad que se encuentra en constante crecimiento, además de que la documentación que se puede encontrar no parece muy claro, entonces que mejor forma de aprender, que una charla en el mismo idioma 😄 .

PD: Esta Charla me gustaría agendarla para el mes de Julio, porque le proximo mes de Junio, no podré realizarla.

Nombre: Juorder Gonzalez

**Comment by fforres** [comment]
Awesome! 👍 
Agendado para Julio entonces!

**Comment by fforres** [comment]
(Sorry... reabriendo @johuder33 )

**Comment by johuder33** [comment]
@fforres no te preocupes, disculpa quería saber cuanto tiempo tendré para la intervención ?

**Comment by DMasterIO** [comment]
@johuder33  master!, tenemos 2 tipos de charlas keynotes [30~45 minutos] o lightning [max 15 minutos]. imagino que para lo que propones la keynote es la que más te acomoda.

**Comment by luchosrock** [comment]
@johuder33 entonces nos confirmas para el 13 de julio? Quedamos atentos :smile:

**Comment by johuder33** [comment]
@luchosrock @DMaster69 @fforres Disculpe no responderles antes lo olvide :s, con respecto a la presentación, tomare un keynote, y sería para el 13 de Julio o el Jueves 6 de Julio ?

**Comment by luchosrock** [comment]
@johuder33 jueves 13 de julio :smile:

**Comment by fforres** [comment]
13 de Julio??! 
Animaciones con RN!??!

Yei!! !!

![giphy 4](https://user-images.githubusercontent.com/952992/27715494-671c054a-5cec-11e7-8b57-bbf0e771dd1f.gif)

**Comment by fforres** [comment]
(Solo de curioso... y bien aparte de la conversa del meetup.... que estas usando para las animaciones @johuder33 ? :P)

**Comment by johuder33** [comment]
@fforres siii Animations :) la verdad no tengo pensado usar alguna librería o algo por el estilo, usare la misma librería de RN Animated y haré las animaciones from scratch jejeje

**Comment by fforres** [comment]
Buenísima master!

-------
Friendly reminder, ojo si con ese estilo de comentarios, la idea es no pasar a llevar a nadie 😄 (Por temas de género, sexualidad, condición o raza)

**Comment by fforres** [comment]
El código de conducta usualmente se lo enviamos a los charlistas, así que paso a dejarlo acá :P https://github.com/Noders/code_of_conduct,

**Comment by johuder33** [comment]
@fforres ah no claro por supuesto, en la charla existirá otra forma de hablar no te preocupes por eso igualmente leeré lo que me enviaste gracias :D

**Comment by luchosrock** [comment]
@johuder33 tienes algúna red social para contactarte?

**Comment by johuder33** [comment]
@luchosrock si por Twitter estaría bien : @johuder33

**Comment by cristofer-dev** [comment]
@johuder33 Gracias por ser parte el meetup y compartir tu experiencia, tu charla estuvo genial! 
Saludos y gracias de parte de la Comunidad de Noders!
