### ISSUE TITLE
Charla Ionic + Firebase: "De la idea al prototipo en un día"

### ISSUE THREAD

**Issue by rcamposp** [Noders/Meetups#4]
A pesar que llevo algún tiempo suscrito a la comunidad, no he tomado la iniciativa de participar en los meetups. Finalmente, este año decidí que me involucraría de forma más activa con las distintas comunidades de desarrolladores en Chile y me gustaría compartir un poco la experiencia de mi última incursión. 

En mi continua búsqueda de un stack que permitiera prototipar una idea de forma rápida, finalmente di con estas herramientas las cuales permiten de forma muy sencilla, primero crear un conjunto de mockups funcionales (Ionic + Ionic Creator) y posteriormente integrar un backend (Firebase + Angularfire) con disponibilidad de actualizaciones en tiempo real de datos.

Creo que es un tema muy relevante y que podría interesar a muchas personas. Se que actualmente existe una comunidad de Ionic en Chile en la cual tratan el tema de esta tecnología. A pesar de lo anterior estoy convencido que darle ese enfoque de integración con Firebase para realizar un prototipo funcional en muy poco tiempo ofrece una ventaja que, hasta el momento, no he visto que otro framework o stack de tecnologías pueda ofrecer.

No soy experto ni mucho menos en el tema, pero la experiencia que tengo podría condensarla en un formato de 30 minutos en el que pueda demostrar las ventajas de utilizar este stack.

Me gustaría saber cómo es el proceso, la dinámica de los eventos y en qué fechas se realizaría el próximo para evaluar la factibilidad de preparar una presentación sobre lo expuesto anteriormente.

De todas maneras estoy abierto a cualquier sugerencia. 

Muchas gracias!

**Comment by Xabadu** [comment]
Hola @rcamposp. Buenísima! Más que bienvenido entonces.

Lo importante es compartir conocimiento, así que desde ya te agradecemos la iniciativa de participar.

El próximo Meetup es el Jueves 4 de Febrero, así que estarías confirmado para abrir ese día. Los eventos los hacemos en las oficinas de Groupon LatAm (Avda. Vitacura 2771, Piso 9) desde las 18:30 a las 21 hrs. Hay 2 charlas o keynotes de 30 mins y 2 lightnings de 5 mins, además de un tiempo antes del inicio de la primera charla y posterior a la última para avisos de la comunidad, networking y otros. Tenemos proyector habilitado y un sector cómodo para exponer, pero de todas formas si necesitas algo adicional, avísanos y lo gestionamos desde ya.

Sobre la charla propiamente tal, si bien no tenemos estructuras rígidas ni fijas, lo recomendable es mantenerse dentro del tiempo estimado (~30 mins) para llevar un buen ritmo y dejar espacio para preguntas que la gente pueda tener. Como lo tuyo incluiría una demo, probablemente hagan varias ;)

Fuera de eso, ten en cuenta que posterior al Meetup subiremos acá al repo las presentaciones y ejemplos de código, así que idealmente no incluir material con información sensible o que no se pueda compartir.

Si tienes cualquier pregunta, no dudes en avisarnos. 

Saludos!

**Comment by rcamposp** [comment]
Perfecto. Necesitarían que les envíe cómo sería la presentación con anticipación? Tengo pensado hacerlo estilo programa de cocina en el que voy mostrando cada uno de los pasos pero para respetar el formato de tiempo, tendré una versión "lista" de cada uno de los pasos y así avanzar más rápidamente.

Al final tendré un prototipo funcionando (que obviamente tendré listo con anticipación) y que todos podrán probar desde su dispositivo.

**Comment by Xabadu** [comment]
Súper, esa es buena idea. En el meetup pasado hubo una presentación similar (con Angular 2), en el cual tenían los pasos separados por branches, lo que le dio buen ritmo a la charla.

Sobre la presentación en si, no es necesario, pero puedes hacerlo si quieres que te demos una opinión antes de presentar ;). Lo único a tener presente es que no haya nada que pase a llevar el Código de Conducta del evento (puedes verlo en http://meetupjs.cl/assets/files/code.pdf).

Saludos!

**Comment by fforres** [comment]
Como estamos para la proxima semana? @rcamposp :)

**Comment by rcamposp** [comment]
Tengo la presentación lista y ahora estoy trabajando en los ejemplos. Así que tendré todo listo!

**Comment by fforres** [comment]
Osom! @rcamposp  :)

**Comment by rcamposp** [comment]
A qué horas es bueno que llegue allá? Asumo que debería llegar un poco antes.

**Comment by Xabadu** [comment]
6:30 está bien @rcamposp. Generalmente los primeros 15-30 mins son para hacer networking y recibir a la gente, así que ahí preparamos todo. 

Saludos!

**Comment by rcamposp** [comment]
Buenísimo. Gracias @Xabadu.

Nos vemos mañana!

**Comment by fforres** [comment]
Ultima consulta @rcamposp 
Si vas a mostrar código, sería genial grabar tu pantalla para subir el video.
No es muy complicado de hacer o si? :smiley_cat:

**Comment by rcamposp** [comment]
No. Yo lo grabo ;)

**Comment by fforres** [comment]
@rcamposp un crá :+1:

**Comment by Xabadu** [comment]
@rcamposp nos compartes tu presentación?

Saludos!

**Comment by rcamposp** [comment]
http://slides.com/rcamposp/deck-1

Gracias @Xabadu y @fforres por la oportunidad.

Seguimos en contacto!

**Comment by Xabadu** [comment]
Buenísima!, Gracias a ti por compartir la charla. Estuvo buenísima.

Lo que necesites, no dudes en avisarnos. Un abrazo!
