### ISSUE TITLE
Centralizar aportes en $

### ISSUE THREAD

**Issue by fforres** [Noders/Meetups#41]
## Motivación
De acuerdo a las ultimas interacciones que hemos tenido con la comunidad en los Meetups anteriores, muchas personas nos han comentado que les gustaría tener alguna manera de aportar con dinero.

Si, hemos logrado cosas súper Cool y es tanto por el apoyo de la comunidad como por el trabajo y tiempo de los organizadores (Muchas Gracias 💓), por lo mismo, sería genial poder canalizar las ganas de ayudar de quienes no pueden disponer del (aveces harto) tiempo para ayudar con la organización.

## Disclaimer:
Mi idea con esto no es juntar 500 mil pesos mensuales con esto, pero podría ayudarnos con alivianar algunos temas como la búsqueda de Sponsors, cervezas, snacks, etc. 

## Opciones:
Que opinan de usar algo como:
https://opencollective.com
o
http://patreon.com

Me gusta más *Opencollective*, permite transparentar los gastos bastante y mostrarle a la comunidad que cualquier $ que estamos gastando, lo que estamos gastando específicamente para los eventos de la comunidad 😄 

### Opiniones?
CC: @Noders/meetup

**Comment by fforres** [comment]
Extra info sobre los % de cobro de las 2 alternativas
### OpenCollective

> Open Collective takes 10% of the money raised by the collective for managing bookkeeping, taxes, and admin (fiscal sponsorship), as well as providing your Open Collective page and the software it runs on. We share this commission with the fiscal sponsor (legal owner of the bank account that holds the money on behalf of the collective).
> Additionally, our payment processors charge a fee - Stripe for receiving money via a Credit Card and PayPal for paying out expenses. Usually 2.9% + $0.30 per transaction. We are exploring adding other means of payment to reduce those fees, including ACH transfers and Bitcoin.

### Patreon
> Our fee is 5% of processed pledges. Payment processing fees vary based on the pledge amount, but are typically under 5% of the total amount you process across all patrons.
> We do not handle most tax payments, but we collect tax identification information and report this to tax authorities as legally required. You are responsible for reporting any taxes.

**Comment by Xabadu** [comment]
Antes de todo, si, 1000%.

Creo que OpenCollective es más cercano a este tipo de iniciativas. Patreon tiene algunos extras interesantes si estás creando constantemente contenido, lo que para este caso quizás no aplique mucho.

Independiente del servicio, creo que lo más importante es definir ciertas cosas que puedan eventualmente convertirse en problemas con gente que vea desde afuera esto y piense que es un intento por monetizar los Meetups y/o actividades que se hagan a futuro. Cosas como:

* **Montos vs Metas:** (cuanto se apunta a juntar, en que momento se para de juntar, etc).
* **A qué se destina la plata que se junta ahí:** Este punto parece sencillo, pero puede no serlo. Hay personas que pueden no estar de acuerdo con, por ej., destinar los fondos para comprar alcohol o ciertos tipos de comida. Creo que la mejor forma de manejar eso es definir expectativas claras desde un inicio y no improvisar/cambiar cosas sobre la marcha, con el fin de que quienes aporten dinero no se sientan "estafados" por algo que se haya prometido y que después cambie.
* **Qué pasa si se junta más de lo necesario**: En el caso de que **si** juntes 500 mil pesos mensuales (?) y para la organización de los Meetups usen una cantidad considerablemente menor, creo que es bueno definir que pasa con los fondos restantes, a que se destinan, etc. 

Se me ocurre eso por ahora, pero una vez más, apoyo 1000% la idea.

**Comment by fforres** [comment]
Vale por el insight @Xabadu 
Personalmente me gusta mucho más la idea de usar OpenCollective, suena mucho más apegado a lo que se busca con Noders. 

Tienes razón con lo de posibles preguntas no vale mucho tener transparencia de lucas si no hay transparencia de intenciones... o roadmap 😕 

**A qué se destina la plata que se junta ahí:** 
  - @Xabadu tiene razón... es complicado sobretodo el tema de snacks (Alcohol, comida vegana, etc) 
    Nunca hemos tenido problemas pero tampoco nunca hemos financiado más que privadamente. 
Creo que las cervezas han funcionado bien, cuando no hemos tenido no ha sido mucho tema... creo que también tendríamos que tener una alternativa no Alcohólica para eventos futuros. (Digo, al predicar ser una comunidad inclusiva deberíamos al menos tener una *coca* además de *baltilocas*)

**Montos vs Metas:** 
  - Creo que no deberíamos limitar el $, es un happy problem si juntamos 12 millones/mes (😆 ), querrá decir que la gente cree en lo que hacemos. (?)
Pero por muy **happy**, no deja de ser un **problema**, deberíamos si o si tener un plan de crecimiento o de que haremos con ese $.

**Qué pasa si se junta más de lo necesario**:
  - (Relacionado al punto anterior) Creo que OpenCollective nos ayuda bastante con eso, podemos tener transparencia en cuanto $ tenemos/gastamos. 
    Una idea es que podemos tener una definición de gastos usuales: i.e.
    - Swag custom  -> 40 USD (Hacer stickers de EventLoop, Nodeschool, Noders, por ejemplo)
    - Importar Swag -> 40 - 50 USD (Traer swag de Github, Firefox, etc)
    - Cervezas para el meetup -> 50 - 60 USD
    - Bebidas para el meetup -> 10 - 20 USD
    - Snacks para meetup -> 70 - 80 USD
    
    O guardar para eventos más grandes, JSConf, eventloop, nodeschool, etc.

Aunque Esto último podría generar problemas, podrían haber casos en plan:
- > Yo ya sé JS, porqué debería pagar para que ustedes enseñen a otras personas?
- > Pero si a mi no me interesan las conferencias, yo voy a los puros meetups.

... serían casos super not cool 😕 

Opiniones?

-----------

TLDR:
Estoy de acuerdo, propongo crear un archivo con detalles de: 
  1. Statement de la comunidad (Que hacemos, por que lo hacemos (?))
  2. En qué usaremos las donaciones.
  3. Aproximados de gastos usuales.
  4. Nuestro roadmap de actividades.

Podemos basarnos en otras comunidades: 
- https://opencollective.com/wwcodeaustin (Me gusta mucho este)
- https://opencollective.com/gdljs
- https://opencollective.com/softcraft

**Comment by cristofer-dev** [comment]
Igual me gusta mas **OpenCollective** esta mas alineado con lo que buscamos para la comunidad creo!

Concuerdo con los puntos mencionados!

Respecto a los casos **not cool**, creo que si se definen bien los **Statement de la comunidad** y a que irán destinados los fondos no deberían haber mayores problemas!

**Comment by Xabadu** [comment]
@L0rdKras @DMaster69 que piensan uds?

**Comment by rodrigoAdones** [comment]
Yo estoy totalmente de acuerdo con la idea de recibir aportes, además de usar OpenCollective para esto. Patreon es más como de artistas, o gente que se hace los fondos para proyectos personales o directamente ganarse la vida, y no realmente para eventos o comunidades, como es nuestro caso.

La transparencia del uso del dinero recibido es algo que debemos cuidar, y es lo mas importante al elegir la plataforma para recibir los aportes.

Debemos estar claros también que al recibir dinero, estamos comprometiéndonos a mostrar mejoras en la organización, por lo que también me parece debemos dejar bien claro y documentado cómo se usará la plata de los aportes, describiendo prioridades, o cómo se administraría el dinero en ciertos tramos, onda si tenemos tanto dinero a tal fecha antes del meetup, se usará en comida y bebidas, si tenemos tanto más, se usará en stickers...etc

**Comment by cristofer-dev** [comment]
Entonces hay que elaborar un borrador de lo que mencionan arriba, 

- Statement 
- En qué usaremos las donaciones.
- Estimación de Gastos
- Roadmap

**Comment by fforres** [comment]
Me parece genial 😄 
En el #43 le podemos hacer seguimiento al documento/borrador

Acá podemos seguir viendo la plataforma para centralizar Aportes en $

**Comment by fforres** [comment]
Tuvimos un update de los chicos de opencollective:

> Unfortunately, the only payment processor we use atm is Stripe, we can't use paypal. (...) If you guys have an account in the US, you could connect that account to Stripe and receive the money for your collective. 

So... la alternativa de Opencollective se ve complicada.
Solo recolectan $ mediante Stripe, y nuestra única manera de crear un opencollective es tener una cuenta bancaria en algún pais q tenga Stripe y conectarlos... 😕 

Patreon se posiciona mejor segun yo.... pero de igual manera, podemos tener opciones :)
Acá hay un post en HackerNews donde muestran varias alternativas para recolectar fondos a proyectos opensource: https://news.ycombinator.com/item?id=11868267

### Opciones

- https://liberapay.com/
- https://gratipay.com/
- https://flattr.com/
- http://www.backerpass.com/
- https://baqqer.com/
- https://snowdrift.coop/

**Comment by cristofer-dev** [comment]
Pense en @Xabadu y su banco gringo ! digo yo!

**Comment by fforres** [comment]
Si, pero ahí entramos en otros temas.
Como stripe se conecta con el banco, empezamos a lidiar con temas de impuestos, fiscal sponsors y cosas que en USA son haaarto más complejas.
Creo yo que no debemos poner a @Xabadu en esa situación. ❤️ 

La opción es buscar alguna alternativa que podamos implementar con menos jaleo :)

**Comment by cristofer-dev** [comment]
Malditos Yankees y su economía!  
Hay que revisar las otras opciones!

**Comment by fforres** [comment]
BTW, esta lectura está super cool, es una comparativa de plataformas de crowdfunding :) 
https://wiki.snowdrift.coop/market-research/other-crowdfunding
