### ISSUE TITLE
Borrador para community-fund

### ISSUE THREAD

**Issue by fforres** [Noders/Meetups#43]
(Para hacerle seguimiento a la creación del documento de recaudación de fondos)

TODO: 

- [ ] Statement
- [ ] En qué usaremos las donaciones.
- [ ] Estimación de Gastos
- [ ] Roadmap

cc @Noders/meetup

**Comment by cristofer-dev** [comment]
para los **Statement** tenemos alguna que nos sirva de referencia ??

**Comment by fforres** [comment]
Les parece basarse en el correo a facebook developer circles? 
Podemos iterar sobre eso 😄

**Comment by fforres** [comment]
COPYPASTE del correo

### Descripción:

En Noders (http://noders.com) creamos y mantenemos una comunidad global alrededor de JavaScript, NodeJS y su ecosistema en LatinoAmérica. 
Es una iniciativa Opensource (http://github.com/noders), non-profit, realizada por y para desarrolladores.
Nuestro enfoque es potenciar el ecosistema de desarrolladores a lo largo de Latino América, realizando para ello meetups, hackatones, conferencias y actividades con la comunidad que permitan el fortalecimiento de la misma.
¿Porqué? Porque nos gusta.

### Historia:

 Noders es una comunidad sin fines de lucro, enfocada en el desarrollo de la comunidad de JS a lo largo de latinoamérica.
Nace en Chile a comienzos del 2015, realizando cursos y actividades, buscando generar espacios, actividades, y crear y apoyar iniciativas que permitan el desarrollo de la comunidad de JavaScript y NodeJS.

Algunas de las actividades realizadas:
Meetups Mensuales de JavaScript
https://www.meetup.com/es/Javascript-Chile/

Talleres de NodeBots

Chapter de NodeSchool Santiago
https://www.facebook.com/nodeschoolsantiago

EventLoop - Hackathón. BigData, Data Visualization, OSS, Javascript y NodeJS
http://eventloop.noders.com

Impacton 2016 - Hackathon de Emprendimiento Social
https://impacton.org/

### Roadmap:

- Conferencia 2018 
- "Expansión" (Motivar la aparición de nuevos meetups, puede ser en tecnologías concretas ReactJS Santiago, Noders Concepción,  NodeJS Temuco)
