### ISSUE TITLE
Nombre cool para iniciativa de Nuevos Meetups

### ISSUE THREAD

**Issue by fforres** [Noders/Meetups#45]
(Relacionado a  ##44)

### Motivación
Sería genial tener un nombre más cool para la iniciativa que estamos generando.
Más que...  ***Iniciativa para que exista una mayor diversidad de meetups*** 😆 

### Idea
Centralizar en este issue un listado de ideas (Y ... razones(?)) para nombres 😄 

### Opciones
- [ ] Lorem ipsum
- [ ] Dolor sit amer

CC @Noders/meetup

**Comment by fforres** [comment]
Propongo:
### Extends.js 
(**Personalmente no me gusta mucho la sintaxis de clases en JS...pero ya qué 😆**)
**Extends** siento que va con el plan de Expandirse/forkear el meetup/replicar la experiencia. 
Also...es una keyword reservada en JS ...que más nerd 😄

**Comment by fforres** [comment]
Ping? @Noders/meetup

**Comment by Xabadu** [comment]
Bien por mi, no tengo preferencias particulares por el nombre, solo una pregunta, Por qué un nombre nuevo y no seguir expandiendo los chapters de Noders?

**Comment by fforres** [comment]
Claaaro, es la idea .
Es mas que nada el nombre que le ponemos a la iniciativa 😄

**Comment by fforres** [comment]
Wait...es confuso? 
Si decimos en un meetup "Recuerden a XXXXXXX, la inciativa que tenemos para abrir más chapters de Noders"

**Comment by fforres** [comment]
Sería super cool dejar esto definido esto antes del meetup, por si quieren recordarle a la gente durante el evento 😄 cc @Noders/meetup

**Comment by cristofer-dev** [comment]
Little Noders... 
Noders Sponsoring...

**Comment by cristofer-dev** [comment]
puta no soy mu creativo para estas weas...

**Comment by luchosrock** [comment]
anda a vaar; :tongue:

**Comment by luchosrock** [comment]
Creo que debiese ser *Noders/xxxxxx* simple y explicativo
