### ISSUE TITLE
Charla vue.js

### ISSUE THREAD

**Issue by csaldiasdev** [Noders/Meetups#46]
## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)

## ¿Cuál es tu nombre?
Cristian Saldias

## ¿Cuál es el título de tu charla?

'Introducción a Vue.js y Vuex + Demo'

## Danos una descripción de tu charla (20 palabras)

La charla tratara de una breve introducción de vue.js. en donde se explicaran los aspectos bases de la librería, ademas de introducir también en vuex. Para terminar, se hará una demostración de una aplicación hecha con vue.js con vuex

## ¿Tienes alguna red social donde podamos contactarte?

https://www.facebook.com/cristian.saldias.p

## ¿Representas a alguna compañía o empresa?
No.

## ¿Quieres agregar algo más?
Nos vemos en el Meetup!

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by luchosrock** [comment]
@cristians90 nos confirmas para el Jueves 13 de julio? :smile:

**Comment by csaldiasdev** [comment]
Si!
de ahí somos.

**Comment by fforres** [comment]
Yeiii!! 
Genial @cristians90 !! :D  

![giphy 5](https://user-images.githubusercontent.com/952992/27715535-d4a1697a-5cec-11e7-971a-2238c4ce725f.gif)

**Comment by fforres** [comment]
Uh! a todo esto master.

Un friendly reminder, me imagino que ya lo sabes, pero no está de más comentarlo 😄 


-----

Los eventos que hacemos se rigen por el siguiente 
[código de conducta](https://github.com/Noders/code_of_conduct), 
Queremos que la gente se sienta incluida y que los meetups son un espacio seguro para cualquier persona, asi que no queremos pasar a llevar a nadie ni herir sensibilidades (ni por temas de género, sexualidad, condición, raza o etcéteras) 

-----


Gracias de nuevo por la disposición 😄

**Comment by cristofer-dev** [comment]
@cristians90 Gracias por ser parte el meetup y compartir tu experiencia, tu charla estuvo genial! 
Saludos y gracias de parte de la Comunidad de Noders!
