### ISSUE TITLE
Charla de Elm

### ISSUE THREAD

**Issue by rogeriochaves** [Noders/Meetups#47]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?

Rogério Chaves

## ¿Cuál es el título de tu charla?
Introducción a Elm: la solución final para el frontend

## Danos una descripción de tu charla (20 palabras)
Voy explicar un poco de la lenguaje Elm, que no es un framework nuevo, pero si una nueva lenguaje puramente funcional y totalmente sin errores para desarrollo de aplicaciones frontend.

## ¿Tienes alguna red social donde podamos contactarte?
https://twitter.com/_rchaves_
https://github.com/rogeriochaves

## ¿Representas a alguna compañía o empresa?
ThoughtWorks

## ¿Quieres agregar algo más?
Nos vemos en el meetup (:

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by rogeriochaves** [comment]
@luchosrock

**Comment by luchosrock** [comment]
@rogeriochaves ya tenemos dos charlas de 20 minutos agendadas para este jueves 13. ¿Es posible que coordinemos para el próximo meetup (primera o segunda semana de agosto)? Quedamos atentos :smile:

**Comment by rogeriochaves** [comment]
no voy estar acá en chile, vuelvo este viernes a brasil :(
quizás en la próxima :)

**Comment by luchosrock** [comment]
@rogeriochaves si te parece bien y aún tienes disponibilidad nos gustaría que participaras, la idea es no perder el tema, quedo atento :smiley:

**Comment by rogeriochaves** [comment]
esta bien! gracias! Igual voy al meetup de cualquier manera y ya tengo la charla lista, si sobra tiempo yo presento ;D

**Comment by cristofer-dev** [comment]
@rogeriochaves Gracias por ser parte el meetup y compartir tu experiencia, tu charla estuvo genial! 
Saludos y gracias de parte de la Comunidad de Noders!

**Comment by rogeriochaves** [comment]
@cristofer-dev muchas gracias! Y para aprovechar, les comparto los slides https://speakerdeck.com/rogeriochaves/introduccion-a-elm
