### ISSUE TITLE
Tiene un minuto para hablar de TDD

### ISSUE THREAD

**Issue by highercomve** [Noders/Meetups#49]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?

Sergio Alejandro Marin Zambrano

## ¿Cuál es el título de tu charla?

"Tiene un minuto para hablar de TDD"

## Danos una descripción de tu charla (20 palabras)
Vamos a hablar un poco de TDD y como implementarlo con Feather, Vuex, Vue y Nuxt. Vamos a revisar un poco mas, como hacer TDD, vamos a probar, probar, probar. Como en programa de cocina donde los pasos ya estan hecho pero los repasan poco a poco.

## ¿Tienes alguna red social donde podamos contactarte?
Twitter, Github: @highercomve

## ¿Representas a alguna compañía o empresa?
UBiome

## ¿Quieres agregar algo más?
Vamos a darle oportunidad a TDD hasta que se nos haga una practica comun, siempre que hablemos de programación.

[Presentacion](https://slides.com/highercomve/tdd)
[Repositorio](https://github.com/highercomve/tdd-nuxt-feathers)
-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by fforres** [comment]
Me encantó la propuesta! @highercomve 👍 

Si puedo te acompaño con una charla 😄

**Comment by highercomve** [comment]
Gracias @fforres ahi coloque los slides en los que estoy trabajando.

**Comment by cristofer-dev** [comment]
Esta cool @highercomve ! El meetup va el **14 de Sptiembre** no tienes problema para esa fecha ?

**Comment by fforres** [comment]
Holas @highercomve  !
Muchas gracias por la presentación en el Meetup :) Sos un sol! 😄 

Esta semana queremos enviar el correo con avisos / presentaciones agradecimientos y demases.

Sería genial si tienes un repo / links / presentación para mandar. O algún aviso (Ofertas laborales, eventos, etc). 

Saludos!

**Comment by highercomve** [comment]
Buenas,

De nada un placer ya quiero hacer otra sobre serverless y aws (flow, TDD,
lambda) suena divertido?

Ahora sobre la anterior.
Repo:
https://github.com/highercomve/tdd-nuxt-feathers
Slides:
https://slides.com/highercomve/tdd/

Y mi Twitter, GitHub, etc

@highercomve

Saludos
