### ISSUE TITLE
"Ahorrándose" el backend

### ISSUE THREAD

**Issue by DMasterIO** [Noders/Meetups#5]
Nombre del charlista: César Encina León

Contacto: twitter.com/dmaster69

Nombre de la charla: Ahorrándose el backend

Descripción de la charla: implementación de una [galería de imágenes](http://ivdevs.com/#gallery) dinámica con github pages + AWS Lambda + Firebase + AWS S3 y un poquito de AngularJS :open_mouth: 

Software Engineer @ autofact.cl

**Comment by Xabadu** [comment]
Súper!, confirmamos tu charla entonces para el meetup del Jueves 4 de Febrero. Recuerda que el material debe estar disponible para que lo podamos subir a este repo posteriormente, por lo que no debe incluir información confidencial ni sensible.

¿Algo que necesites de nuestra parte para ayudar con tu presentación?

Saludos!

**Comment by rcamposp** [comment]
Hola @DMaster69. Yo también utilizaría Firebase en mi charla si vas al issue #4 podrás ver un poco más a detalle lo que tengo pensado hacer.

Yo hablaré por encima de Firebase y no entraré mucho en el detalle. Al final mi mensaje es: "puedes hacer un prototipo funcional y escalable rápidamente usando este stack de tecnologías". Pero creo que sería bueno no repetirnos. @Xabadu y @DMaster69 Cómo lo ven ustedes?

**Comment by Xabadu** [comment]
Buen punto @rcamposp. En teoría no debiesen toparse mucho, ya que ambos usan Firebase como parte del stack y no el actor principal. @DMaster69 debiese darnos más detalles ahí.

Saludos!

**Comment by fforres** [comment]
No conozco mucho de como funciona, o si es muy poco JS, pero darle más enfoque a lambda que a firebase podría funcionar @DMaster69 ?

Por otro lado, podríamos conseguir una charla con otro framework de BaaS/DaaS y mover una de las keynotes

**Comment by DMasterIO** [comment]
Sorry la demora ( Full pega hoy :P ), básicamente pensaba hacer lo que dice @fforres enfocarme un poco más en como funciona lambda y básicamente nombrar firebase y angular solo nombrarlos por encima para no repetir lo que dirá  @rcamposp, al igual que githubpages, además lo mi presentación la tenia pensada más como un lighting de 10 minutos aprox. por lo cual tampoco dará como para algo más profundo

**Comment by fforres** [comment]
Como vamos pa mañana @DMaster69  :+1:

**Comment by DMasterIO** [comment]
Todo bien @fforres, necesitas que te envíe los slides antes o algo por el estilo?

**Comment by fforres** [comment]
Nah, si vas a mostrar código, sería genial grabar tu pantalla :-) :heart: 
No es muy complejo o si? :smiley_cat:

**Comment by DMasterIO** [comment]
@fforres  Bueno siempre lo tuve pensado como una lighting y he estado alargándola para cubrir la keynote :P ... algo así como codear en vivo no lo haré, pero si explicaré código que esta funcionando y tengo los repos en github. si aún así necesitas que grabe confírmame y bajo algún programilla luego

**Comment by fforres** [comment]
@DMaster69 Osom! Confirmado entonces! :+1:

**Comment by DMasterIO** [comment]
@fforres  @Xabadu Link de las slides => http://slides.com/cesarencinaleon/ahorrandose-el-backend/

**Comment by Xabadu** [comment]
Buenísima @DMaster69! ¿Pudiste grabar tu pantalla también?

Saludos!
