### ISSUE TITLE
Typescript en el mundo real (Mitos y verdades)

### ISSUE THREAD

**Issue by raerpo** [Noders/Meetups#51]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [X] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Rafael Poveda

## ¿Cuál es el título de tu charla?
Typescript en el mundo real

## Danos una descripción de tu charla (20 palabras)
¿Que tal funciona typescript en los proyectos que tenemos en el día a día? Me gustaría compartir mi visión de como usar typescript más allá del "get started" y revisar algunos mitos y verdades sobre Typescript.

## ¿Tienes alguna red social donde podamos contactarte?
Github o Twitter: @raerpo

## ¿Representas a alguna compañía o empresa?
Adessa Falabella

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by cristofer-dev** [comment]
Gracias @raerpo por sumarte con tu keynote!. El meetup esta programado para el **14 de Septiembre** no tienes problemas para esa fecha ?

**Comment by raerpo** [comment]
Si, esta perfecto.
allá nos vemos entonces!

**Comment by fforres** [comment]
Holas @raerpo !
Muchas gracias por la presentación en el meetup :) Estuvo de pelos. Más de alguno quedaron convencidos de probar typescript (Incluso por sobre Flow)

Te cuento que queremos esta semana enviar el correo con avisos / las presentaciones.
Sería genial si tienes un repo / links / presentación para mandar. O algún aviso (Ofertas laborales, eventos, etc) 

Saludos!

**Comment by raerpo** [comment]
Muchas gracias @fforres este es el repo de los slides:
https://github.com/raerpo/typescript-talk

Con respecto a las ofertas laborales, seguimos buscando frontends (ojala con conocimientos React pero es más importante que sepan JS y aprendan rápido). Currículos al correo repovedal@falabella.cl

PD: Gracias por la oportunidad de hablar en noders! gran comunidad... Felicitaciones!
