### ISSUE TITLE
Documentando APIs de manera automática

### ISSUE THREAD

**Issue by mishuagopian** [Noders/Meetups#52]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Michel Agopian

## ¿Cuál es el título de tu charla?
'Documentando APIs de manera automática'

## Danos una descripción de tu charla (20 palabras)
La documentación siempre es un problema en los proyectos. En esta charla nos gustaría poder compartir nuestra experiencia sobre [una herramienta que desarrollamos](https://github.com/wolox/dictum.js) para poder documentar nuestras APIs de manera automática y tener un desarrollo más sustentable.

## ¿Tienes alguna red social donde podamos contactarte?
Twitter: [mishuagopian](https://twitter.com/mishuagopian)
Github: [mishuagopian](https://twitter.com/mishuagopian)

## ¿Representas a alguna compañía o empresa?
[Wolox](wolox.com.ar)

## ¿Quieres agregar algo más?
Soy Ingeniero en Informática, vivo en Buenos Aires, Argentina y actualmente estoy trabajando en un proyecto en Santiago durante el mes de septiembre, por lo que me pareció copado poder compartir las experiencias que traemos de otro país!

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by fforres** [comment]
Wow, esta muy cool @mishuagopian 
Estarás solo para septiembre? (Estarás acá en Octubre?) Tenemos ya 2 keynotes para este meetup, no tengo muy claro si podemos sumar una tercera, dejame confirmar y te cuento :)

**Comment by mishuagopian** [comment]
@fforres estaré solamente en Septiembre! Puedo hacerla no muy extensa, pero de verdad que me encantaría poder participar con la charla!!

**Comment by mishuagopian** [comment]
@fforres noticias sobre esto? :)

**Comment by enBonnet** [comment]
@mishuagopian Hello! Te esperamos con tu charla y todo el buen animo que tienes!

**Comment by mishuagopian** [comment]
@enBonnet Gracias!

**Comment by fforres** [comment]
Holas @mishuagopian !
Antes que nada, muchas gracias por la presentación en el meetup :) estuvo de pelos.
Queremos esta semana enviar el correo con avisos / las presentaciones.

Sería genial si tienes un repo / links / presentación para mandar. O algún aviso (Ofertas laborales, eventos, etc) 

Saludos!
