### ISSUE TITLE
Intro a GraphQL: APIs flexibles y eficientes

### ISSUE THREAD

**Issue by dortegan** [Noders/Meetups#53]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Daniel Antonio Ortega Norambuena

## ¿Cuál es el título de tu charla?
Intro a GraphQL: APIs flexibles y eficientes
La idea es mostrar qué es GraphQL, como funciona y sus principales características. Además se mostrará una demo con un ejemplo sencillo.

## Danos una descripción de tu charla (20 palabras)
GraphQL: qué es, como funciona y principales características. Además se muestra una demo.

## ¿Tienes alguna red social donde podamos contactarte?
https://dortegan.github.io

## ¿Representas a alguna compañía o empresa?
[ComparaOnline](http://www.comparaonline.cl)

## ¿Quieres agregar algo más?

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by luchosrock** [comment]
Hola! la charla sería el próximo miércoles 04 de Octubre, nos confirmas tu participación?

Saludos 😄

**Comment by dortegan** [comment]
Si! confirmo.

Saludos

**Comment by luchosrock** [comment]
Gracias @dortegan por tu presentación!! Es posible que nos compartas las slides? 😄 quedamos atentos!!
