### ISSUE TITLE
Nodejs everywhere

### ISSUE THREAD

**Issue by enBonnet** [Noders/Meetups#54]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Ender Bonnet

## ¿Cuál es el título de tu charla?
Aplicaciones y usos comunes que tiene Nodejs

## Danos una descripción de tu charla (20 palabras)
Un recorrido ilustrado por las aplicaciones que usamos día a día escritas con Nodejs/Javascript 

## ¿Tienes alguna red social donde podamos contactarte?
Twitter: @enbonent
GitHub: @enbonnet

## ¿Representas a alguna compañía o empresa?
No

## ¿Quieres agregar algo más?
JavaScript es amor

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by Xabadu** [comment]
![austin-beer](https://user-images.githubusercontent.com/3161019/31142597-9b38564c-a82f-11e7-9023-2538588018df.gif)
