### ISSUE TITLE
lightning : Ordenando entradas rss por votos

### ISSUE THREAD

**Issue by juanpabloaj** [Noders/Meetups#55]
## ¿Qué tipo de presentación quieres hacer?

- [ ] Keynote (20 a 30 minutos)
- [x] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?

Juan Pablo Abarzúa J

## ¿Cuál es el título de tu charla?
Ordenando entradas RSS por votos de reddit y hackernews

## Danos una descripción de tu charla (20 palabras)
Cuando tienes muchas entradas rss, por ejemplo https://github.com/kilimchoi/engineering-blogs , Cómo saber cuál es la más comentada? en esta presentación mostraré una forma de ordenar las entradas por popularidad.

## ¿Tienes alguna red social donde podamos contactarte?
github.com/juanpabloaj
twitter.com/juanpabloaj

## ¿Quieres agregar algo más?

No está implementado en javascript sino en python, aunque el método es general, se podría implementar el cualquier lenguaje y quizás a alguien le pueda ser de utilidad.

Está alojado en https://zeit.co/now, también quiero mostrar como funciona ese servicio 
Acá funcionando 
https://entries-by-votes.now.sh/

**Comment by fforres** [comment]
Cerrando el issue @juanpabloaj por limpieza :p
Puede reabrirlo acá sin problemas https://github.com/Noders/Meetups/issues/new
