### ISSUE TITLE
Lightning Talk: Configurando un proyecto Phaser en Typescript y Webpack

### ISSUE THREAD

**Issue by BlackHarpy** [Noders/Meetups#56]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [ ] Keynote (20 a 30 minutos)
- [x] Lightning Talk (+- 5 minutos)
- [x] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
María Castro

## ¿Cuál es el título de tu charla?
 Configurando un proyecto Phaser en Typescript y Webpack

## Danos una descripción de tu charla (20 palabras)

Una pequeña charla sobre la configuración inicial necesaria para empezar a desarrollar en Phaser usando Typescript y Webpack

## ¿Tienes alguna red social donde podamos contactarte?

https://github.com/BlackHarpy

## ¿Representas a alguna compañía o empresa?
SimpliRoute

## ¿Quieres agregar algo más?
El Lightning no viene en representación de una empresa, es solo un proyecto personal pero en mi lugar de trabajo estamos en búsqueda de un Desarrollador Fullstack así que quiero aprovechar para dar el aviso también.

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by cristofer-dev** [comment]
\o/ Genial @BlackHarpy !!! Te tinca para diciembre ??

**Comment by BlackHarpy** [comment]
Por supuesto! :dancer:

**Comment by BlackHarpy** [comment]
Por cierto... pendientes con la fecha del proximo meetup. Háganlo el primer jueves porque el segundo es día de Star Wars :D

**Comment by enBonnet** [comment]
@BlackHarpy Reprogramamos el meetup para el jueves 14 de diciembre

**Comment by BlackHarpy** [comment]
Ya, ahí estaré. Trasnochada, pero estare xD

**Comment by cristofer-dev** [comment]
@BlackHarpy usarás un equipo con salida HDMI ? u otro conector ?

**Comment by BlackHarpy** [comment]
Sí, un equipo con HDMI. Solo que no es un Apple así que no se si estoy rompiendo alguna regla y me van a juzgar silenciosamente 😄

**Comment by cristofer-dev** [comment]
Jajajaja! Don't worry! Todos los SO son bienvenidos! \o/

**Comment by cristofer-dev** [comment]
Hola @BlackHarpy, todo listo para mañana ?

Después del meetup enviaremos el mail a los asistentes, crees que nos puedas ayudar con el link de tus slides para incluirlo ?

**Comment by BlackHarpy** [comment]
Hola Cristofer! Sí, esperemos! :smile: 

Y por supuesto, aquí tienes el link! https://blackharpy.github.io/talks/phaser-typescript-webpack/index.html

**Comment by cristofer-dev** [comment]
@BlackHarpy nos dejas aquí la info de reclutamiento que quieren publicar :)

**Comment by BlackHarpy** [comment]
Si! Aquí está el enlace a nuestro anuncio https://www.getonbrd.cl/empleos/programacion/desarrollador-full-stack-simplit-solutions

**Comment by fforres** [comment]
Cerrando el issue! 
Gracias por la charla @BlackHarpy 😄
