### ISSUE TITLE
The Wolf of Bitfinex: Usando la API de Bitfinex para crear alertas del mercado de criptomonedas

### ISSUE THREAD

**Issue by pankas87** [Noders/Meetups#57]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [X] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Leonardo Graterol

## ¿Cuál es el título de tu charla?
The Wolf of Bitfinex: Usando la API de Bitfinex para crear alertas del mercado de criptomonedas

## Danos una descripción de tu charla (20 palabras)
La charla parte con yet another introducción a las criptomonedas, un repaso básico de como funcionan y cuáles son las más populares.

Luego de eso un repaso de que es y como funciona Bitfinex, uno de los exchanges de criptomonedas más populares.

Y para la parte final, ahora si nos vamos a ensuciar las manos con código, creando una aplicación de consola pequeña que se conecte a la API pública de Bitfinex para extraer datos de trading en tiempo real y calcular algunos indicadores financieros importantes (Bollinger Bands, RSI, WMA) que podemos usar para crear alertas de buenos momentos para comprar o vender monedas.

## ¿Tienes alguna red social donde podamos contactarte?
Twitter: @pankas87

## ¿Representas a alguna compañía o empresa?
Globant, aunque la charla es a título personal

## ¿Quieres agregar algo más?
Esta charla tiene bastante contenido, por el repaso inicial que se hace sobre el tema de criptomonedas, y es probable que se extienda más allá de los 30 minutos, espero que no sea un inconveniente.

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by cristofer-dev** [comment]
Wow! Genial @pankas87  \o/

**Comment by pankas87** [comment]
Chicos, me salió un evento importante de mi empresa el 7 de diciembre en la noche. Voy a tener que posponer mi propuesta de charla para el siguiente meetup.

**Comment by cristofer-dev** [comment]
No problem! Lo agendamos para el meetup de Enero 2018! Éxito en el evento!

**Comment by cristofer-dev** [comment]
@pankas87 reprogramado para el Jueves 14 de Dic!

**Comment by pankas87** [comment]
@cristofer-dev copiado!

**Comment by cristofer-dev** [comment]
@pankas87 usarás un equipo con salida HDMI ? u otro conector ?

**Comment by pankas87** [comment]
@cristofer-dev HDMI

**Comment by cristofer-dev** [comment]
Hola @pankas87, todo listo para mañana ?

Después del meetup enviaremos el mail a los asistentes, crees que nos puedas ayudar con el link de tus slides para incluirlo ?

**Comment by cristofer-dev** [comment]
@pankas87 nos dejas el link de las slides para incluirlas en el mail :)

**Comment by pankas87** [comment]
Hola @cristofer-dev no había visto esta notificación...

Acá está el link de los slides, saludos :-)

https://github.com/pankas87/the-wolf-of-bitfinex-slides

**Comment by fforres** [comment]
Cerrando el issue! 
Gracias por la charla @pankas87  😄
