### ISSUE TITLE
[Keynote] La Nueva Era del front-end en Groupon LatAm 

### ISSUE THREAD

**Issue by alexandereb** [Noders/Meetups#58]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [x] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Alexander Espinoza

## ¿Cuál es el título de tu charla?
La Nueva Era del front-end en Groupon LatAm (el nacimiento de un nuevo bebe :baby:)

## Danos una descripción de tu charla (20 palabras)
Explicar a grandes rasgos los desafios, soluciones, arquitectura, stack tecnológico y mucho más que envuelve todo el frontend de Groupon LatAm

## ¿Tienes alguna red social donde podamos contactarte?
https://twitter.com/alexander_eb

## ¿Representas a alguna compañía o empresa?
Groupon LatAm

## ¿Quieres agregar algo más?

La charla esta más enfocada a mostrar por un lado como un grupo pequeño de personas tomaron ciertas deciciones para usar un Stack completamente de JS para hacer desde cero todo el frontend de GrouponLatam. Dentro de esto podremos ver problemas resueltos, criterios más detallados en temas técnicos y el día a día del equipo Front. 

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by fforres** [comment]
Esta awesome dude!! :D Metaal!!
Mandamos el aviso con el update mañana :)

**Comment by cristofer-dev** [comment]
Hola @alexandereb , todo listo para mañana ? 

Después del meetup enviaremos el mail a los asistentes, crees que nos puedas ayudar con el link de las slides para incluirlo ?

**Comment by alexandereb** [comment]
@cristofer-dev les puedo mandar el link mañana? antes de la charla ya que estoy afinando algunos detalles :nail_care:

**Comment by cristofer-dev** [comment]
Genial! Gracias @alexandereb ! :)

**Comment by cristofer-dev** [comment]
@alexandereb nos dejan el link de las slides y la info del reclutamiento para enviar el mail  :)

**Comment by fforres** [comment]
Cerrando el issue! 
Gracias por la charla @alexandereb  😄
