### ISSUE TITLE
Desarrollo de bots con Node.js y Microsoft Bot Framework

### ISSUE THREAD

**Issue by marcelofelman** [Noders/Meetups#60]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Marcelo Felman

## ¿Cuál es el título de tu charla?

'Desarrollo de bots con Node.js y Microsoft Bot Framework'

## Danos una descripción de tu charla (20 palabras)

La charla es un aterrizaje al mundo de los bots para developers. La idea es en media hora poder llevarte los conceptos generales, arquitecturas y mejores prácticas para desarrollo de bots con Node.js (en general) pero también con Microsoft Bot Framework (en particular). 

La charla es una adaptación mucho más corta de este MOOC: aka.ms/cursobots

Usualmente el foco es en el código, hay mucha demo, y a veces por los tiempos tangencialmente llegamos a ver procesamiento de lenguaje natural con Machine Learning.

## ¿Tienes alguna red social donde podamos contactarte?

@mfelman en Twitter
@marcelofelman en GitHub

## ¿Representas a alguna compañía o empresa?
Microsoft Corp

## ¿Qué tipo de conector tiene tu notebook?

- [ ] HDMI
- [x] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?
Recibí la invitación/sugerencia del groso de @enBonnet 

Entiendo que para una comunidad abierta como la suya, a veces pueda resultar chocante traer un orador de una compañía en particular que busque posicionar ciertos productos o tecnologías. Mi compromiso con esto es dejar de lado la obsecuencia y tener una charla transparente con la audiencia. Obviamente, sin ignorar el foco en estos productos de Microsoft (que son los que naturalmente mejor conozco), pero sí cuidando la objetividad de por qué algo puede "estar bueno" o no :)

Gracias!!!

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by cristofer-dev** [comment]
Hola @marcelofelman muchas gracias por sumarte como charlista para el meetup!
Estamos agendando el meetup para el **Jueves 11 de Enero 2018** no te complica la fecha ?

**Comment by marcelofelman** [comment]
Ya te puedo confirmar que 11 de enero me queda perfecto

**Comment by cristofer-dev** [comment]
Gracias @marcelofelman ! 
Nos vemos el 11 entonces! :)

**Comment by cristofer-dev** [comment]
Hola @marcelofelman esta todo listo para este jueves! \o/

Post meetup enviaremos un resumen y nos gustaría incluir las **slides**, **links** o **información** que quieras hacer llegar a la comunidad, seria genial si nos dejas aquí la información.

Gracias de nuevo por apoyarnos y nos vemos el jueves. :)

**Comment by marcelofelman** [comment]
Hecho, dale!

**Comment by cristofer-dev** [comment]
@marcelofelman Gracias por ser parte el meetup y compartir tu experiencia, tu charla estuvo genial y estaremos encantados de recibirte nuevamente cuando gustes.

Saludos y gracias de parte de la Comunidad de Noders!
