### ISSUE TITLE
Foto Navideña para collage!

### ISSUE THREAD

**Issue by fforres** [Noders/Meetups#64]
Queremos mandar una foto / collage navideña! necesitamos sus fotos locas @Noders/core

**Comment by fforres** [comment]
@L0rdKras 
@enBonnet 
@DMaster69 
@cristofer-dev 
@fforres
@Xabadu 
@luchosrock

**Comment by cristofer-dev** [comment]
Movida a https://github.com/Noders/Comunicaciones/issues/22
