### ISSUE TITLE
[Charla] - Estos últimos 3 aÑoders 🎂 (Y que se nos viene!)

### ISSUE THREAD

**Issue by fforres** [Noders/Meetups#65]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)

## ¿Cuál es tu nombre?
Felipe Torres  @fforres

## ¿Cuál es el título de tu charla?
`Estos últimos 3 aÑoders 🎂`

## Danos una descripción de tu charla (20 palabras)
- Un cierre de los 3 últimos años, lo que fue, y lo que se viene en `Noders`

## ¿Tienes alguna red social donde podamos contactarte?
- http://twitter.com/fforres
- http://github.com/fforres
- http://fforr.es/

## ¿Representas a alguna compañía o empresa?
A Noders :p 

## ¿Qué tipo de conector tiene tu notebook?
- [x] USB-C

## ¿Quieres agregar algo más?
Nones! :D 

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by cristofer-dev** [comment]
Hola @fforres esta todo listo para este jueves! \o/

Post meetup enviaremos un resumen y nos gustaría incluir las **slides**, **links** o **información** que quieras hacer llegar a la comunidad, seria genial si nos dejas aquí la información.

Gracias de nuevo por apoyarnos y nos vemos el jueves. :)

**Comment by cristofer-dev** [comment]
@fforres Gracias por ser parte el meetup y compartir tu experiencia, tu charla estuvo genial y estaremos encantados de recibirte nuevamente cuando gustes.

Saludos y gracias de parte de la Comunidad de Noders!

**Comment by fforres** [comment]
Gracias dude :)
EL meetup estuvo genial
