### ISSUE TITLE
Keynote: Aprendizajes de trabajar con Phaser

### ISSUE THREAD

**Issue by pctroll** [Noders/Meetups#66]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)

## ¿Cuál es tu nombre?

Jorge Palacios

## ¿Cuál es el título de tu charla?

'Aprendizajes de trabajar con Phaser'

## Danos una descripción de tu charla (20 palabras)

Recopilatorio de técnicas y experiencias de trabajar en distintos proyectos con Phaser en el último año

## ¿Tienes alguna red social donde podamos contactarte?

Twitter: @pctroll
Github: pctroll
LinkedIn: pctroll

## ¿Representas a alguna compañía o empresa?

Noup.

## ¿Qué tipo de conector tiene tu notebook?

- [x] USB-C
- [x] HDMI

## ¿Quieres agregar algo más?

Charla para Meet Up de Febrero 2018.

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by cristofer-dev** [comment]
Genial @pctroll ! Nos Vemos en febrero!

**Comment by cristofer-dev** [comment]
Hola @pctroll Queremos hacer el meetup el **Jue 08 de Feb** te viene bien esa fecha?

**Comment by pctroll** [comment]
Hola muchachos,

Sí! =)

------------------------------------------
*Jorge Palacios*
http://jorge.palacios.co/

**Comment by pankas87** [comment]
Grande [edited] @pctroll!

**Comment by Xabadu** [comment]
Hola @pankas87,

Editamos tu comentario, ya que va contra el código de conducta. Por favor no los hagas a futuro.

**Comment by pankas87** [comment]
Hola @Xabadu! Sorry, Jorge es amigo mío y es apodo de uso entre nosotros, pero entiendo perfectamente, no lo repetiré. Saludos

**Comment by Xabadu** [comment]
@pankas87 Gracias!

**Comment by cristofer-dev** [comment]
Todo listo para el Jueves @pctroll ! Te esperamos! \o/

**Comment by cristofer-dev** [comment]
@pctroll Gracias por ser parte el meetup y compartir tu experiencia, tu charla estuvo genial y estaremos encantados de recibirte nuevamente cuando gustes.

Enviaremos un resumen y nos gustaría incluir las slides de tu presentación, seria genial si nos dejas aquí la información

Saludos y gracias de parte de la Comunidad de Noders!

**Comment by pctroll** [comment]
Buen día chicos,

Muchas gracias por recibirme. Estaré actualizando la presentación para
hacerla más amigable al modo offline de las personas que no pudieron
asistir y quieran sacarle mayor provecho. Espero tenerla lista durante el
fin de semana.




------------------------------------------
*Jorge Palacios*
http://jorge.palacios.co/


2018-02-09 0:05 GMT-03:00 Cristofer <notifications@github.com>:
