### ISSUE TITLE
Una mirada rápida a WebAssembly

### ISSUE THREAD

**Issue by nicoavila** [Noders/Meetups#67]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Lightning Talk (+- 5 minutos)

## ¿Cuál es tu nombre?
Nicolás Ávila

## ¿Cuál es el título de tu charla?
'Una mirada rápida a WebAssembly'

## Danos una descripción de tu charla (20 palabras)
Definición, importancia y potencial de WebAssembly

## ¿Tienes alguna red social donde podamos contactarte?

* [https://twitter.com/nicoavila_a](https://twitter.com/nicoavila_a)
* [https://github.com/nicoavila](https://github.com/nicoavila)

## ¿Representas a alguna compañía o empresa?
No

## ¿Qué tipo de conector tiene tu notebook?

- [x] HDMI

## ¿Quieres agregar algo más?
No por el momento ;)

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by cristofer-dev** [comment]
Hola @nicoavila , la Lightning se ve super cool! que tal para presentarla el **11 de Enero** ?

**Comment by nicoavila** [comment]
Hola @cristofer-dev. Claro! El Jueves 11 de Enero ahi estaré

**Comment by cristofer-dev** [comment]
Hola @nicoavila esta todo listo para este jueves! \o/

Post meetup enviaremos un resumen y nos gustaría incluir las **slides**, **links** o **información** que quieras hacer llegar a la comunidad, seria genial si nos dejas aquí la información.

Gracias de nuevo por apoyarnos y nos vemos el jueves. :)

**Comment by nicoavila** [comment]
Hola @cristofer-dev! Genial! Estoy muy contento de contar con la oportunidad
Les enviaré las slides de la lightning dentro del día
Gracias a ustedes. Hasta mañana!

**Comment by nicoavila** [comment]
Hola! Adjunto las slides y repositorio con código de la lightning de mañana: **Una mirada rápida a WebAssembly**

* [SLIDES](https://github.com/nicoavila/una_mirada_rapida_webassembly/raw/master/slides/lightning_slides.pdf)
* [REPOSITORIO](https://github.com/nicoavila/una_mirada_rapida_webassembly)

Hasta mañana!

**Comment by enBonnet** [comment]
Gracias @nicoavila nos vemos hoy!

Gracias por formar parte del tercer aniversario.

**Comment by cristofer-dev** [comment]
@nicoavila Gracias por ser parte el meetup y compartir tu experiencia, tu charla estuvo genial y estaremos encantados de recibirte nuevamente cuando gustes.

Saludos y gracias de parte de la Comunidad de Noders!

**Comment by nicoavila** [comment]
Gracias a ustedes por darme la oportunidad. Son una excelente comunidad.
Me anotaré con otras cosas para el futuro.

Saludos!! 😃
