### ISSUE TITLE
Webs descentralizadas via blockchain y torrent

### ISSUE THREAD

**Issue by Yhozen** [Noders/Meetups#68]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?
- [ ] Keynote (20 a 30 minutos)
- [x] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Gabriel Pérez

## ¿Cuál es el título de tu charla?
Webs descentralizadas via blockchain y torrent

## Danos una descripción de tu charla (20 palabras)

Quiero presentar un proyecto propio llamado, por el momento, steemsites, el cual da el poder de crear páginas webs sin necesidad de un dominio ni hosting gracias al blockchain de Steem y a la libreria WebTorrent
## ¿Tienes alguna red social donde podamos contactarte?

https://github.com/Yhozen

## ¿Representas a alguna compañía o empresa?
No
## ¿Qué tipo de conector tiene tu notebook?

- [x] HDMI
- [x] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?

salu2

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by luchosrock** [comment]
@Yhozen muchas gracias por contactarnos!! Es posible que agendemos tu charla para Febrero? Cuéntanos cómo está tu disponibilidad para la primera o segunda semana de ese mes 😄 
Quedamos atentos!!

Saludos!!

**Comment by Yhozen** [comment]
Hasta el momento si podría en febrero, si llegara a no poder aviso por aca

**Comment by cristofer-dev** [comment]
Hola @Yhozen Queremos hacer el meetup el **Jue 08 de Feb** te viene bien esa fecha?

**Comment by Yhozen** [comment]
Si puedo esa fecha

**Comment by luchosrock** [comment]
Excelente!!! Nos vemos el 8! 😄  Saludos!!

**Comment by cristofer-dev** [comment]
Todo listo para el Jueves @Yhozen ! Te esperamos! \o/

**Comment by cristofer-dev** [comment]
@Yhozen Gracias por ser parte el meetup y compartir tu experiencia, tu charla estuvo genial y estaremos encantados de recibirte nuevamente cuando gustes.

Enviaremos un resumen y nos gustaría incluir las slides de tu presentación, seria genial si nos dejas aquí la información

Saludos y gracias de parte de la Comunidad de Noders!

**Comment by Yhozen** [comment]
Gracias por la oportunidad! Aquí dejo las [slides](https://drive.google.com/file/d/136DINLRsj4ejv3IdNnWUu0cbPmv4VQTL/view?usp=drivesdk) que usé
