### ISSUE TITLE
[Charla] Node.js: with performance in mind

### ISSUE THREAD

**Issue by atma** [Noders/Meetups#69]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)

## ¿Cuál es tu nombre?

Oleh Burkhay @atma

## ¿Cuál es el título de tu charla?

`Node.js: with performance in mind`

## Danos una descripción de tu charla (20 palabras)

Compartiendo experiencia de uso de Node en una compañía tan grande como Mercado Libre donde performance tiene impacto directo a negocio.

## ¿Tienes alguna red social donde podamos contactarte?

https://twitter.com/oburkhay

## ¿Representas a alguna compañía o empresa?

Mercado Libre

## ¿Qué tipo de conector tiene tu notebook?

- [x] HDMI

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by cristofer-dev** [comment]
Hola @atma esta todo listo para este jueves! \o/

Post meetup enviaremos un resumen y nos gustaría incluir las **slides**, **links** o **información** que quieras hacer llegar a la comunidad, seria genial si nos dejas aquí la información.

Gracias de nuevo por apoyarnos y nos vemos el jueves. :)

**Comment by cristofer-dev** [comment]
@atma Gracias por ser parte el meetup y compartir tu experiencia, tu charla estuvo genial y estaremos encantados de recibirte nuevamente cuando gustes.

Saludos y gracias de parte de la Comunidad de Noders!
