### ISSUE TITLE
Aplicar agilidad en tu empresa: Tests unitarios con Mocha

### ISSUE THREAD

**Issue by nriesco** [Noders/Meetups#7]
Actualmente trabajo con una serie de librerías que son implementadas usando tests y que luego se transforman en un módulo en npmjs.

Esto permite trabajar en forma segura, aplicando BDD/TDD con automatización a un 100% Por otra parte permite reutilizar fácilmente las librerías y tener un control absoluto de sus versiones.

**Comment by Xabadu** [comment]
Hola @nriesco, buenísima! Es un tremendo tema :D 

¿Algo en lo que necesites ayuda de nuestra parte?

Sobre la charla en si, aparte de lo que sale en el Readme, solo recordar que después del Meetup lo ideal es compartir la presentación, por lo que asegúrate de que no tenga información sensible o confidencial.

Adicionalmente, si puedes grabar tu pantalla, sería genial, así preparamos videos de tu charla y la subimos posteriormente.

Quedamos atentos a la confirmación. Gracias!

**Comment by nriesco** [comment]
@Xabadu La idea es mostrar una forma de trabajo que permite ocupar los tests como una ayuda real. He intentado hacer TDD mil veces antes sin éxito pero al utilizar las herramientas correctas todo fluye realmente.

La idea es mostrar lo siguiente:
1. como funciona lo básico de npm (npm install básicamente)
2. como ocupar ese módulo
3. como publicarlo, modificarlo, todo con tests

Todo ese ciclo se transforma en un proceso muy simple, seguro y "controlado" que es lo que quiero mostrar.

Una parte será pública y permitirá hacer el proceso completo pero para hacerlo más entretenido puedo mostrar un par de sitios de verdad, cómo le hago un cambio y lo fácil que resulta aplicarlos. Esos códigos no los puedo dejar pero sí puedo mostrar como hice el cambio. Para esto solamente necesito ocupar mi computador y listo.

Con respecto a la fecha, en teoría el 3 de marzo voy a estar fuera de Chile, pero si no resulta (sería lamentable) me inscribo para ese meetup.

Saludos

**Comment by nriesco** [comment]
@Xabadu Estimado, lamentablemente mi viaje no resultó por lo que sí estaré disponible para el meetup. Confirmado para este jueves.

Como te comentaba anteriormente solamente necesito conectar mi computador y si necesito internet me cuelgo de mi teléfono o de wifi si hay disponible.

Finalmente confirmar si será en Groupon nuevamente y la duración que puede tener.
Saludos

**Comment by fforres** [comment]
Hey @nriesco !

Antes que nada, gracias por tu disposición, el tema se lee genial :smile: 

Estamos intentando mover el Meetup para la siguiente semana, el Jueves 10 de Marzo, ¿Te complica mucho? 

Saludos!

**Comment by nriesco** [comment]
No hay problema eso sí tendría que presentar segundo por la hora.
Slds

**Comment by fforres** [comment]
Eres el mejor @nriesco  :+1: 
Mandaremos el update ahora mismo.

**Comment by Xabadu** [comment]
@nriesco tienes tus slides subidos a algún lado? De ser así, nos envías el link para agregarlos al repo por favor? Gracias!

**Comment by nriesco** [comment]
Estimado, lo prometido..

Proyecto (incluye una aplicación que utiliza la librería):
    https://github.com/nriesco/mocha-unit-test https://github.com/nriesco/mocha-unit-test
Presentación:
    https://www.dropbox.com/s/pk8bxh1ywtdmos8/20160310%20Presentaci%C3%B3n.zip?dl=0 https://www.dropbox.com/s/33svmx82m5ztty7/presentaci%C3%B3n%20mocha.zip?dl=0
Video:
    https://www.dropbox.com/s/3s3kohyoqrcqi4s/20160310%20Pantalla.mov?dl=0 https://www.dropbox.com/s/3s3kohyoqrcqi4s/20160310%20Pantalla.mov?dl=0

Páginas relacionadas:
    https://mochajs.org/ https://mochajs.org/
    http://webdriver.io/ http://webdriver.io/
    http://phantomjs.org/ http://phantomjs.org/
    http://www.seleniumhq.org/ http://www.seleniumhq.org/
    https://github.com/groupon/testium https://github.com/groupon/testium

Saludos

**Comment by Xabadu** [comment]
Gracias!
