### ISSUE TITLE
Jugando con Shaders en WebGL

### ISSUE THREAD

**Issue by bitnenfer** [Noders/Meetups#71]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Felipe Alfonso

## ¿Cuál es el título de tu charla?
Jugando con Shaders en WebGL

## Danos una descripción de tu charla (20 palabras)

Intro a WebGL enfocado a programación de shaders utilizando GLSL. Tocaré tópicos básicos de programación 3D y finalmente armaré un pequeño demo utilizando solo shaders.

## ¿Tienes alguna red social donde podamos contactarte?

[https://twitter.com/bitnenfer/](https://twitter.com/bitnenfer/)
[https://github.com/bitnenfer/](https://github.com/bitnenfer/)

## ¿Representas a alguna compañía o empresa?
No

## ¿Qué tipo de conector tiene tu notebook?

- [x] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?

--

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by cristofer-dev** [comment]
Hola @bitnenfer queremos hacer el meetup el **Jue 08 de Feb** te viene bien esa fecha?

**Comment by bitnenfer** [comment]
Hola, @cristofer-dev. 
El Jueves 8 de Febrero esta bien para mi. Gracias!
Saludos

**Comment by luchosrock** [comment]
Excelente!! Nos vemos el 8 😃 Saludos!!

**Comment by cristofer-dev** [comment]
Todo listo para el Jueves @bitnenfer  ! Te esperamos! \o/

**Comment by cristofer-dev** [comment]
@bitnenfer Gracias por ser parte el meetup y compartir tu experiencia, tu charla estuvo genial y estaremos encantados de recibirte nuevamente cuando gustes.

Enviaremos un resumen y nos gustaría incluir las slides de tu presentación, seria genial si nos dejas aquí la información

Saludos y gracias de parte de la Comunidad de Noders!

**Comment by bitnenfer** [comment]
@cristofer-dev Muchas gracias por la oportunidad, fue muy entretenido y agradable.

[https://github.com/bitnenfer/noders-gl/](https://github.com/bitnenfer/noders-gl/) Este es el repositorio donde están las slides en formato PDF y ademas de la version web.

Saludos!
