### ISSUE TITLE
CSS Grid - Marzo (2018)

### ISSUE THREAD

**Issue by katguzmann** [Noders/Meetups#72]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Kat Guzmán

## ¿Cuál es el título de tu charla?

Mejorando la experiencia Front-End con CSS Grid

## Danos una descripción de tu charla (20 palabras)

En la charla se expondrá como CSS Grid cambia la manera en la que creamos layouts y cómo hacerlo con código limpio y semántico.

## ¿Tienes alguna red social donde podamos contactarte?

https://twitter.com/katguzmann
https://github.com/katguzmann

## ¿Representas a alguna compañía o empresa?
Sosafe

## ¿Qué tipo de conector tiene tu notebook?

- [x] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by enBonnet** [comment]
Wojo! Yes! :smiley:

**Comment by cristofer-dev** [comment]
Wow! Gracias @katguzmann por sumarte como charlista y compartir con nosotros tú experiencia! \o/ 
Nos vemos en el meetup de Marzo!

**Comment by cristofer-dev** [comment]
Hola @katguzmann , la sala para hoy es la A302! 
Nos vemos en el meetup! :)

**Comment by katguzmann** [comment]
Gracias @cristofer-dev , nos vemos! :)

**Comment by cristofer-dev** [comment]
@katguzmann Gracias por ser parte el meetup y compartir tu experiencia, tu charla estuvo genial y estaremos encantados de recibirte nuevamente cuando gustes.

Enviaremos un resumen y nos gustaría incluir las slides de tu presentación, seria genial si nos dejas aquí la información

Saludos y gracias de parte de la Comunidad de Noders!

**Comment by katguzmann** [comment]
Ningún problema Cristofer, ¡subo las slides durante el fin de semana! :)

**Comment by katguzmann** [comment]
Aquí están las slides http://slides.com/katguzman/cssgrid :)

**Comment by cristofer-dev** [comment]
Gracias @katguzmann \o/
