### ISSUE TITLE
Keynote: Construyendo aplicaciones web para escritorio con Electron

### ISSUE THREAD

**Issue by BlackHarpy** [Noders/Meetups#73]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
María Castro

## ¿Cuál es el título de tu charla?

Construyendo aplicaciones web para escritorio con Electron

## Danos una descripción de tu charla (20 palabras)

Un overview de Electron, cómo funciona y cómo usarlo para construir aplicaciones web en JavaScript para Escritorio

## ¿Tienes alguna red social donde podamos contactarte?

Github: [BlackHarpy](https://github.com/BlackHarpy)
Twitter: [@BlackHarpy](https://twitter.com/BlackHarpy)

## ¿Representas a alguna compañía o empresa?
SimpliRoute

## ¿Qué tipo de conector tiene tu notebook?

- [x] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?
Charla para el Meetup de Marzo 2018

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by cristofer-dev** [comment]
Wow! Gracias @BlackHarpy por sumarte como charlista y compartir con nosotros tú experiencia! \o/
Nos vemos en el meetup de Marzo! ;)

**Comment by cristofer-dev** [comment]
Hola @BlackHarpy, la sala para hoy es la A302! 
Nos vemos en el meetup! :)

**Comment by BlackHarpy** [comment]
Muchas gracias por la info!

Nos vemos allá! :purple_heart:

**Comment by cristofer-dev** [comment]
@BlackHarpy Gracias por ser parte el meetup y compartir tu experiencia, tu charla estuvo genial y estaremos encantados de recibirte nuevamente cuando gustes.

Enviaremos un resumen y nos gustaría incluir las slides de tu presentación, seria genial si nos dejas aquí la información

Saludos y gracias de parte de la Comunidad de Noders!

**Comment by BlackHarpy** [comment]
Hola Cristofer. Gracias a ud por recibirme.

Acá esta el enlace a los slides de la charla https://blackharpy.github.io/talks/electron-basics/index.html#/

Saludos!

**Comment by cristofer-dev** [comment]
Gracias de nuevo @BlackHarpy ! \o/
