### ISSUE TITLE
Event loop y asincronia en otros universos

### ISSUE THREAD

**Issue by lcjury** [Noders/Meetups#74]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [X] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Luis Jury

## ¿Cuál es el título de tu charla?
Event loop y asincronia en otros universos

## Danos una descripción de tu charla (20 palabras)
Una pequeña revisión de como funciona el Event loop en Javascript, porqué es importante, y como podemos tener sus beneficios en otros lenguajes.

## ¿Tienes alguna red social donde podamos contactarte?
https://twitter.com/lcjury

## ¿Representas a alguna compañía o empresa?
No

## ¿Qué tipo de conector tiene tu notebook?

- [X] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?
No

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by fforres** [comment]
Awesome @lcjury !! 👍 
Buenísimo topic para la charla!!

**Comment by enBonnet** [comment]
Excelente! @lcjury Te gustaría hacer esta charla en el meetup de abril? 🥇

**Comment by lcjury** [comment]
Añopa para abril :)!

**Comment by cristofer-dev** [comment]
Hola @lcjury  estamos coordinando el espacio para el 05 o 12 de abril, te complica alguna de las fechas ?

**Comment by lcjury** [comment]
@cristofer-dev Ningún problema ;)!

**Comment by mortegac** [comment]
Buen tema @lcjury  ahora a esperar la charla..

**Comment by fforres** [comment]
Mi cerebro acaba de cachar que me voy a perder la charla de @lcjury  :( 
> Habrá que grabarla (?)

**Comment by lcjury** [comment]
@fforres Nunca es tarde para empezar a hacer streaming :P

**Comment by tatymoly** [comment]
@mortegac  a ver si a esa si vas :P. Podemos hablar con Ender para tratar de hacer streaming. Yo también me la perderé... 💔

**Comment by mortegac** [comment]
@tatymoly. Pero porque me extrañas tanto. 😜    Si en la burgerjs estuvimos al lado.     No me. pierdo La próxima ☺️

**Comment by cristofer-dev** [comment]
Hola @lcjury ya tenemos fecha y lugar, para el meetup, **Jueves 12 de abril** en **Centro Comunitario Bellavista**, Constitución 85, Providencia. (Metro Baquedano) \o/

**Comment by cristofer-dev** [comment]
@lcjury gracias por ser parte el meetup y compartir tu experiencia, tu charla estuvo genial y estaremos encantados de recibirte nuevamente cuando gustes.

Enviaremos un resumen y nos gustaría incluir las slides de tu presentación, seria genial si nos dejas aquí la información

Saludos y gracias de parte de la Comunidad de Noders!

**Comment by cristofer-dev** [comment]
Gracias @lcjury \o/

[eventloop.pdf](https://github.com/Noders/Meetups/files/1917597/eventloop.pdf)
