### ISSUE TITLE
Programación reactiva con RxJS y observables

### ISSUE THREAD

**Issue by pankas87** [Noders/Meetups#75]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Leonardo Graterol

## ¿Cuál es el título de tu charla?
Programación reactiva con RxJS y observables

## Danos una descripción de tu charla (20 palabras)
Manejando eventos asíncronos de forma reactiva, usando observables de RxJS. Algunos ejemplos de eventos que se pueden manejar: Interacción con el usuario, comunicación con WebSockets.

## ¿Tienes alguna red social donde podamos contactarte?
@pankas87 en la mayoría de redes sociales

## ¿Representas a alguna compañía o empresa?
No

## ¿Qué tipo de conector tiene tu notebook?

- [x ] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by cristofer-dev** [comment]
Genial @pankas87 por sumarte como charlista y compartir con nosotros tú experiencia! \o/
Te tinca Abril ?

**Comment by pankas87** [comment]
Sí, Abril está perfecto

**Comment by cristofer-dev** [comment]
Gracias! 👍

**Comment by pankas87** [comment]
Hola @cristofer-dev, me surgieron algunas cosas y ando trabajando en varios proyectos, me queda super difícil dar la charla en Abril ¿La podemos mover para Mayo?

**Comment by cristofer-dev** [comment]
Hola @pankas87 , claro, ningún problema. 
La movemos a Mayo y gracias de nuevo por apoyarnos y compartir tu experiencia con la comunidad! \o/

**Comment by cristofer-dev** [comment]
Hola @pankas87 gracias de nuevo por sumarte como charlista. Ya tenemos fecha y lugar, **jueves 10 de mayo a las 19:00** en ***constitución 85, providencia*. Nos cuentas si puedes en esa fecha.

**Comment by pankas87** [comment]
Hola @cristofer-dev, sí, si puedo, alllí estaré.

Una consulta, este sprint en el trabajo estuve implementando algunas cosas en express que me gustaría exponer antes que esto de RxJS ¿Puedo cambiar el tema de la charla?

**Comment by luchosrock** [comment]
@pankas87 También puedes crear otro issue con el tema nuevo y dejar esta charla para otra ocasión (le sacamos el tag de mayo y se lo asignamos al nuevo issue). Qué te parece? 😄

**Comment by pankas87** [comment]
@luchosrock perfecto! Ahora creo el otro issue!

**Comment by pankas87** [comment]
Listo muchachos, ya creé el otro issue

**Comment by cristofer-dev** [comment]
Gracias @pankas87 !!! Agendamos la nueva issue para ser presentada en MAYO :)

**Comment by enBonnet** [comment]
Máster @pankas87  estamos confirmando ¿Aún tienes la disponibilidad de hacer la charla el 11 de octubre en las oficinas de ComparaOnline? Saludos
