### ISSUE TITLE
Introducción a la IA de juegos con Phaser

### ISSUE THREAD

**Issue by pctroll** [Noders/Meetups#76]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Jorge Palacios

## ¿Cuál es el título de tu charla?

Introducción a la IA de juegos con Phaser

## Danos una descripción de tu charla (20 palabras)

Ejemplos prácticos de IA para juegos utilizando JS con Phaser enfocados en comportamientos cinemáticos

## ¿Tienes alguna red social donde podamos contactarte?

Twitter: pctroll
GitHub: pctroll
LinkedIn: pctroll

## ¿Representas a alguna compañía o empresa?
No

## ¿Qué tipo de conector tiene tu notebook?

- [x] HDMI
- [x] USB-C
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?
Postulación para Abril

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by cristofer-dev** [comment]
Genial @pctroll por sumarte como charlista y compartir con nosotros tú experiencia! \o/
Te tinca Abril ?

**Comment by pctroll** [comment]
Sí, justo coloqué Abril en comentarios jaja :)

------------------------------------------
*Jorge Palacios*
http://jorge.palacios.co/

**Comment by cristofer-dev** [comment]
Cierto! Siento lo despistado! Anotado para Abril ! :) Y gracias !

**Comment by pctroll** [comment]
No hay problema, jaja.

Nos vemos!!
[insert celebration dab here]

------------------------------------------
*Jorge Palacios*
http://jorge.palacios.co/

**Comment by cristofer-dev** [comment]
Hola @pctroll estamos coordinando el espacio para el 05 o 12 de abril, te complica alguna de las fechas ?

**Comment by pctroll** [comment]
Hola Cristofer,

Ambas me quedan bien.

------------------------------------------
*Jorge Palacios*
http://jorge.palacios.co/

**Comment by cristofer-dev** [comment]
Hola @pctroll ya tenemos fecha y lugar, para el meetup, **Jueves 12 de abril** en **Centro Comunitario Bellavista**, Constitución 85, Providencia. (Metro Baquedano) \o/

**Comment by cristofer-dev** [comment]
@pctroll gracias por ser parte el meetup y compartir tu experiencia, tu charla estuvo genial y estaremos encantados de recibirte nuevamente cuando gustes.

Enviaremos un resumen y nos gustaría incluir las slides de tu presentación, seria genial si nos dejas aquí la información

Saludos y gracias de parte de la Comunidad de Noders!

**Comment by pctroll** [comment]
Hola muchachos, estaré publicando todo el material en el siguiente repositorio:

https://github.com/pctroll/aigamesphaser
