### ISSUE TITLE
Creando escenas 3D con Three.js

### ISSUE THREAD

**Issue by tatymoly** [Noders/Meetups#77]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [ ] Keynote (20 a 30 minutos)
- [x] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Tatiana Molina

## ¿Cuál es el título de tu charla?

Creando escenas 3D con Three.js

## Danos una descripción de tu charla (20 palabras)

Ejemplo básico de seteo de escena, camara, iluminación y renderizado de un objetos 3D en Web con Three.js

## ¿Tienes alguna red social donde podamos contactarte?

Twitter: tatymolys
Github: tatymoly

## ¿Representas a alguna compañía o empresa?
No
## ¿Qué tipo de conector tiene tu notebook?

- [x] HDMI
- [ ] Mini DisplayPort
- [x] VGA

## ¿Quieres agregar algo más?

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by enBonnet** [comment]
Yaju! Excelente taty 😄

**Comment by fforres** [comment]
Dope!!! 😄 
QUe lata no estar ahi para verla :(

**Comment by cristofer-dev** [comment]
Hola @tatymoly , la sala para hoy es la A302! 
Nos vemos en el meetup! :)

**Comment by tatymoly** [comment]
:heart: gracias cris :3

**Comment by cristofer-dev** [comment]
@tatymoly Gracias por ser parte el meetup y compartir tu experiencia, tu charla estuvo genial y estaremos encantados de recibirte nuevamente cuando gustes.

Enviaremos un resumen y nos gustaría incluir las slides de tu presentación, seria genial si nos dejas aquí la información

Saludos y gracias de parte de la Comunidad de Noders!

**Comment by tatymoly** [comment]
Hola @cristofer-dev  gracias por el apoyo 😄 . Dejo mis slides y repositorios:

**- Siledes:** http://slides.com/tatianamolina/threejs-1#/
**- Repo 1:** https://github.com/tatymoly/threejs-basics
**- Repo 2:** https://github.com/tatymoly/three_monkey
**- Link Threejs:** https://threejs.org/

**Comment by cristofer-dev** [comment]
Gracias @tatymoly \o/
