### ISSUE TITLE
Logo!

### ISSUE THREAD

**Issue by fforres** [Noders/Meetups#8]
Jugando con photoshop hoy PM

No soy un cra del diseño, asi que tengo los PSD por si alguien quiere jugar :smile: 

Opiniones @Xabadu @jorgevenegas @comunacho 

![jscl_logo_1](https://cloud.githubusercontent.com/assets/952992/12874423/79fafe2a-cdb2-11e5-9e99-d7f925635fa5.png)
![jscl_logo_2](https://cloud.githubusercontent.com/assets/952992/12874422/79f959a8-cdb2-11e5-9870-9c1cb0108b54.png)

**Comment by JonDotsoy** [comment]
Me gusta el primero 👍.

**Comment by fforres** [comment]
Si :D Tenemos que darle más contraste si, hicimos un batch y no se nota mucho la forma de chile en el sticker.
@JonDotsoy
