### ISSUE TITLE
Creando una sala online 3D con websockets y three.js

### ISSUE THREAD

**Issue by DvdQzd** [Noders/Meetups#80]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [ ] Keynote (20 a 30 minutos)
- [x] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
David Quezada

## ¿Cuál es el título de tu charla?

Creando una sala online 3D con websockets y three.js

## Danos una descripción de tu charla (20 palabras)

Pequeño ejemplo de como sería crear una sala online al estilo VRChat, pero sin Ugandan Knuckles por todos lados.

## ¿Tienes alguna red social donde podamos contactarte?

Twitter: @BloodyLink_
Github: BloodyLink
Facebook: /david.quezada.m

## ¿Representas a alguna compañía o empresa?
No.
## ¿Qué tipo de conector tiene tu notebook?

- [x] HDMI
- [ ] Mini DisplayPort
- [x] VGA

## ¿Quieres agregar algo más?

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by cristofer-dev** [comment]
Genial @BloodyLink, Gracias por sumarte como charlista! Dejamos agendado para Junio! \o/

**Comment by cristofer-dev** [comment]
Hola @BloodyLink te viene bien el **14 de Junio** ?

**Comment by DvdQzd** [comment]
Buena fecha @cristofer-dev

**Comment by cristofer-dev** [comment]
Genial!

**Comment by DvdQzd** [comment]
@cristofer-dev Hola. Es posible correr mi charla a estas alturas? He tenido N pega, tramites y un cambio de casa en trámite. No creo tener el tiempo de terminar una charla decente para Junio :c 
Onda, dejarla pendiente, sin fecha por ahora u -u

**Comment by cristofer-dev** [comment]
Ningún problema @BloodyLink ! La dejamos para Julio ??

**Comment by cristofer-dev** [comment]
Hola @BloodyLink gracias nuevamente por sumarte como charlista!
Te parece bien presentar en **Jueves 12 de Julio** ?
