### ISSUE TITLE
Cómo trabajar desde casa sin volverte loco

### ISSUE THREAD

**Issue by marcelofelman** [Noders/Meetups#81]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [ ] Keynote (20 a 30 minutos)
- [x] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Marcelo Felman

## ¿Cuál es el título de tu charla?

'Cómo trabajar desde casa sin volverte loco'

## Danos una descripción de tu charla (20 palabras)

Quisiera compartir mi experiencia como developer/ingeniero casi 100% remoto. Qué cosas me han funcionado bien, qué cosas no, y qué tips creo que podrían servirle a toda la comunidad.

## ¿Tienes alguna red social donde podamos contactarte?

Twitter: mfelman
GitHub: marcelofelman

## ¿Representas a alguna compañía o empresa?
Trabajo en Microsoft Corp, pero este contenido es a nivel personal.

## ¿Qué tipo de conector tiene tu notebook?

- [ ] HDMI
- [x] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?
Sé que este contenido no está estrictamente relacionado con Node, pero considero que puede ser útil para toda la comunidad :)

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by cristofer-dev** [comment]
Hola @marcelofelman gracias por sumarte nuevamente como charlista y compartir tu experiencia con la comunidad. Estamos coordinando el espacio para el 05 o 12 de abril, te complica alguna de las fechas ?

**Comment by marcelofelman** [comment]
Perfecto! En ambas fechas puedo!

**Comment by cristofer-dev** [comment]
Hola @marcelofelman ya tenemos fecha y lugar, para el meetup, **Jueves 12 de abril** en **Centro Comunitario Bellavista**, Constitución 85, Providencia. (Metro Baquedano) \o/

**Comment by marcelofelman** [comment]
Excelente! Ahí nos vemos 🤙

**Comment by fforres** [comment]
Sorry que haga un highjack del issue, pero tendras un correo donde contactarte @marcelofelman ?

**Comment by marcelofelman** [comment]
mfelman [at] microsoft

**Comment by marcelofelman** [comment]
Estimadísimos, voy a estar llegando al meetup aprox. a las 19:30hs, ojalá antes. Lo aclaro para no tomar la primer charla. Espero que no haya problema!

**Comment by tatymoly** [comment]
Perfecto @marcelofelman no hay problema. Te esperamos!! 😄

**Comment by cristofer-dev** [comment]
@marcelofelman gracias por ser parte el meetup y compartir tu experiencia, tu charla estuvo genial y estaremos encantados de recibirte nuevamente cuando gustes.

Enviaremos un resumen y nos gustaría incluir las slides de tu presentación, seria genial si nos dejas aquí la información

Saludos y gracias de parte de la Comunidad de Noders!

**Comment by marcelofelman** [comment]
Muchas gracias a ustedes. Un placer como siempre! 

Acá el contenido: https://github.com/marcelofelman/presentations/blob/master/Como%20trabajar%20desde%20tu%20casa.pdf

Abrazo!

**Comment by cristofer-dev** [comment]
Gracias @marcelofelman !
