### ISSUE TITLE
Introducción al desarrollo de juegos multi-player

### ISSUE THREAD

**Issue by pctroll** [Noders/Meetups#82]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Jorge Palacios

## ¿Cuál es el título de tu charla?

Introducción al desarrollo de juegos multi-player

## Danos una descripción de tu charla (20 palabras)

Introducción al desarrollo de juegos multi-player utilizando Phaser, Node.js y Socket.io

## ¿Tienes alguna red social donde podamos contactarte?

Twitter: https://twitter.com/pctroll
GitHub: @pctroll

## ¿Representas a alguna compañía o empresa?
Noup

## ¿Qué tipo de conector tiene tu notebook?

- [x] HDMI
- [x] USB-C
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?
Para presentarla en Mayo 2018.

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by tatymoly** [comment]
Hola @pctroll  muchas gracias por tu postulación. Aún estamos revisando y coordinando las fechas, por lo que no podemos confirmarte que quedará para Mayo. Te estaremos informando al respecto. Gracias!! 😃

**Comment by cristofer-dev** [comment]
Gracias @pctroll por sumarte como charlista y compartir con nosotros tú experiencia! \o/
Te parece bien presentar en **Junio** ?

**Comment by pctroll** [comment]
Sí, está genial. =)

**Comment by pctroll** [comment]
Hola @cristofer-dev, veo que tiene el tag de Junio; quería confirmar que está asegurada y así armar lo necesario para la charla =)

**Comment by cristofer-dev** [comment]
Hola @pctroll , si, te viene bien el **14 de Junio** ?

**Comment by pctroll** [comment]
Pues sí, mejor que mejor. Planificaré todo para esa fecha.

GRACIAS!

------------------------------------------
*Jorge Palacios*
http://jorge.palacios.co/

**Comment by cristofer-dev** [comment]
Genial!

**Comment by cristofer-dev** [comment]
@pctroll gracias por ser parte el meetup y compartir tu experiencia, tu charla estuvo genial y estaremos encantados de recibirte nuevamente cuando gustes.

Enviaremos un resumen y nos gustaría incluir las slides de tu presentación, seria genial si nos dejas aquí la información

Saludos y gracias de parte de la Comunidad de Noders!

**Comment by pctroll** [comment]
Hola Cristofer,

Adjunto las láminas. Sin embargo, a final de semana estaré en contacto
contigo o Ender a través de Slack para una versión mejorada con más
información para quienes no pudieron asistir. Las envío en este momento
porque sé que el resumen viene pronto jaja.

Un abrazo!
------------------------------------------
*Jorge Palacios*

**Comment by cristofer-dev** [comment]
[Slides](https://github.com/Noders/Meetups/files/2135189/Introduccion.a.juegos.multiplayer.pdf)
