### ISSUE TITLE
Stan, monitoreando aplicaciones Nodejs 

### ISSUE THREAD

**Issue by julia-leyton** [Noders/Meetups#83]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Julia Leyton
## ¿Cuál es el título de tu charla?

Stan, monitoreando aplicaciones Nodejs en 20 minutos (o menos)

## Danos una descripción de tu charla (20 palabras)

Presentación de Instana, que usa Machine Learning y AI para monitorear aplicaciones dinámicas, microservicios y containers (con ayuda de Stan)
## ¿Tienes alguna red social donde podamos contactarte?

Facebook: https://www.facebook.com/jvlia.antiare
Linkedin: https://www.linkedin.com/in/julia-leyton-2930732a/

## ¿Representas a alguna compañía o empresa?
Sí, Instana
## ¿Qué tipo de conector tiene tu notebook?

- [] HDMI
- [x] Mini DisplayPort
- [] VGA

## ¿Quieres agregar algo más?
Necesitaría conexión Wifi
Sobre el conector de mi notebook, tengo adaptadores tanto para VGA como para HDMI

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by julia-leyton** [comment]
chicos, les dejo mi mail por si acaso: julia@impulseit.com

**Comment by tatymoly** [comment]
Hola @julia-leyton de acuerdo a lo conversado te vamos a contactar por correo para coordinarnos. Gracias!! 😄❤️

**Comment by cristofer-dev** [comment]
Hola @julia-leyton gracias de nuevo por sumarte como charlista. Ya tenemos fecha y lugar, **jueves 10 de mayo a las 19:00** en ***constitución 85, providencia*. Nos cuentas si puedes en esa fecha.

**Comment by julia-leyton** [comment]
Hola Cristofer,
gracias a ustedes por recibirnos, ningún problema el 10 de mayo!

**Comment by cristofer-dev** [comment]
@julia-leyton gracias por ser parte el meetup y compartir tu experiencia, tu charla estuvo genial y estaremos encantados de recibirte nuevamente cuando gustes.

Enviaremos un resumen y nos gustaría incluir las slides de tu presentación, seria genial si nos dejas aquí la información.

Saludos y gracias de parte de la Comunidad de Noders!

**Comment by julia-leyton** [comment]
Hola Cristofer! Nuevamente gracias a ustedes por recibirnos, me sentí muy bienvenida y fue un agrado compartir con ustedes! Muy buena comunidad :) Aquí les dejo el pdf de la presentación 
[Stan-Meetup-20180510.pdf](https://github.com/Noders/Meetups/files/1997082/Stan-Meetup-20180510.pdf)

Saludos y nos vemos!
Julia
