### ISSUE TITLE
Introducción a Two.js

### ISSUE THREAD

**Issue by tatymoly** [Noders/Meetups#84]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?

Tatiana Molina

## ¿Cuál es el título de tu charla?

Introducción a Two.js

## Danos una descripción de tu charla (20 palabras)

Conceptos y ejemplos básicos con Two.js ✏️ 

## ¿Tienes alguna red social donde podamos contactarte?

Twitter: @tatymolys
Github: @tatymoly

## ¿Representas a alguna compañía o empresa?
Nope
## ¿Qué tipo de conector tiene tu notebook?

- [x] HDMI
- [ ] Mini DisplayPort
- [x] VGA

## ¿Quieres agregar algo más?
❤️

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by cristofer-dev** [comment]
Gracias @tatymoly por sumarte como charlista y compartir con nosotros tú experiencia! \o/
Te parece bien presentar en **Junio** ?

**Comment by tatymoly** [comment]
Hola @cristofer-dev me complica un poco Junio, podría dejar on hold esta charla? Si quieres cierra el issue y la vuelvo a abrir apenas tenga mas tiempo 😓

**Comment by cristofer-dev** [comment]
Ningún problema @tatymoly, cerraremos el issue por ahora, y tú nos cuentas apenas puedas sumarte como charlista!
