### ISSUE TITLE
Feathers && NuxtJS: the last real-time™ Jedis

### ISSUE THREAD

**Issue by betacar** [Noders/Meetups#85]
## ¿Qué tipo de presentación quieres hacer?

- [X] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Carlos Betancourt

## ¿Cuál es el título de tu charla?
Feathers && NuxtJS: the last real-time™ Jedis

## Danos una descripción de tu charla (20 palabras)
A través de Feathers, Nuxt, Vue, y Vuex, construiremos una aplicación de sincronización de texto en tiempo real entre múltiples clientes.

## ¿Tienes alguna red social donde podamos contactarte?

* [Twitter](https://twitter.com/betacar)
* [Github](https://github.com/betacar)

## ¿Qué tipo de conector tiene tu notebook?

- [X] HDMI
- [X] Mini DisplayPort
- [ ] VGA

**Comment by cristofer-dev** [comment]
Genial @betacar por sumarte como charlista y compartir con nosotros tú experiencia! \o/
Estamos coordinando fecha y lugar para los próximos meetups, apenas tengamos la información te confirmamos!

**Comment by fforres** [comment]
Que awesome! :D  Y que fomo al mismo tiempo :'(

**Comment by cristofer-dev** [comment]
Hola @betacar gracias de nuevo por sumarte como charlista. Ya tenemos fecha y lugar, **jueves 10 de mayo a las 19:00** en ***constitución 85, providencia*. Nos cuentas si puedes en esa fecha.

**Comment by betacar** [comment]
@cristofer-dev ¡Perfecto! Cuenten conmigo.

**Comment by cristofer-dev** [comment]
Hola @betacar gracias de nuevo por sumarte como charlista. Te tinca presentar tu charla el **jueves 14 de junio a las 19:00** ?

**Comment by betacar** [comment]
Of course, @cristofer-dev!

**Comment by betacar** [comment]
- Presentación:
  - [PDF](https://speakerdeck.com/betacar/feathers-and-nuxtjs-the-last-real-time-jedis?slide=1).
  - [Repo](https://github.com/betacar/feathers-nuxt-realtime).
- [Demo](https://github.com/betacar/feathers-nuxt-jedis).

**Comment by mortegac** [comment]
@betacar  Excelente presentación.  Se agradece!

**Comment by cristofer-dev** [comment]
@betacar gracias por ser parte el meetup y compartir tu experiencia, tu charla estuvo genial y estaremos encantados de recibirte nuevamente cuando gustes.

Incluiremos las slides de tu presentación en el mail post meetup! 

Saludos y gracias de parte de la Comunidad de Noders!
