### ISSUE TITLE
Promise y manejo de sincronía | El gran dolor de cabeza de los programadores de NodeJs

### ISSUE THREAD

**Issue by aljvilla** [Noders/Meetups#86]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Manuel Villafañe

## ¿Cuál es el título de tu charla?
Promise y manejo de sincronía
El gran dolor de cabeza de los programadores de NodeJs

## Danos una descripción de tu charla (20 palabras)
Es bien sabido que cualquier programador al entrar al maravilloso mundo de NodeJs, el primer dilema que se le presenta es como manejar la sincronía cuando se trabaja con promise o callback (a mi me paso y creanme que lloré sangre 😊).

## ¿Tienes alguna red social donde podamos contactarte?

- [Github](https://github.com/aljvilla)
- [Linkedin](https://www.linkedin.com/in/manuel-villafa%C3%B1e-473b5983/)

## ¿Representas a alguna compañía o empresa?
[MuvSmart](https://muvsmart.com/)
## ¿Qué tipo de conector tiene tu notebook?

- [x] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by cristofer-dev** [comment]
Genial @aljvilla por sumarte como charlista y compartir con nosotros tú experiencia! \o/
Estamos coordinando fecha y lugar para los próximos meetups, apenas tengamos la información te confirmamos!

**Comment by aljvilla** [comment]
Perfecto quedo atento saludos . . .

**Comment by aljvilla** [comment]
Hola Cristofer, te comento que si necesitan un lugar para los meetups podemos coordinarlo en las instalaciones del lugar donde trabajo, solo es cuestión de fijar una fecha, cantidad estimada de asistentes y listo.

Quedo atento saludos . . .

**Comment by cristofer-dev** [comment]
Wow genial @aljvilla lo coordinamos via mail! :)

**Comment by cristofer-dev** [comment]
Hola @aljvilla gracias nuevamente por sumarte como charlista!
Te parece bien presentar en **Jueves 12 de Julio** ?

**Comment by aljvilla** [comment]
Hola Cristofer, si genial.

Donde sería?? recuerda que podemos coordinas hacer el evento en las instalaciones de las oficinas donde trabajo.

**Comment by cristofer-dev** [comment]
Genial @aljvilla sería en **Centro Comunitario Bellavista, en constitución 85** 
Te debemos un meetup en tus oficinas, lo coordinaremos \o/!
Gracias de nuevo por el apoyo y las ganas! :)

**Comment by cristofer-dev** [comment]
Gracias @aljvilla por ser parte el meetup y compartir tu experiencia, tu charla estuvo genial y estaremos encantados de recibirte nuevamente cuando gustes.

Enviaremos un resumen con las slides de tu presentación.

Saludos y gracias de parte de la Comunidad de Noders!

[promise.pdf](https://github.com/Noders/Meetups/files/2193490/promise.pdf)
