### ISSUE TITLE
Dale sabor a tu JS con un poco de Curry(ing)()

### ISSUE THREAD

**Issue by pankas87** [Noders/Meetups#87]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Leonardo Graterol

## ¿Cuál es el título de tu charla?
Dale sabor a tu JS con un poco de Curry(ing)()

## Danos una descripción de tu charla (20 palabras)
La charla muestra un caso de uso práctico donde se implementa el currying de funciones en un servicio web Express, para crear objetos singleton-like únicos para cada request

## ¿Tienes alguna red social donde podamos contactarte?
Twitter: @pankas87

## ¿Representas a alguna compañía o empresa?

Globant

## ¿Qué tipo de conector tiene tu notebook?

- [x] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by cristofer-dev** [comment]
Gracias @pankas87 ! Nos vemos el **jueves 10 de mayo a las 19:00** en **constitución 85, providencia.** Nos cuentas si puedes en esa fecha.

**Comment by pankas87** [comment]
Hola @cristofer-dev, sí allá estaré, nos vemos!

**Comment by cristofer-dev** [comment]
@pankas87 gracias por ser parte el meetup y compartir tu experiencia, tu charla estuvo genial y estaremos encantados de recibirte nuevamente cuando gustes.

Enviaremos un resumen y nos gustaría incluir las slides de tu presentación, seria genial si nos dejas aquí la información que quieras compartir.

Saludos y gracias de parte de la Comunidad de Noders!

**Comment by pankas87** [comment]
@cristofer-dev Cristofer, muchas gracias a ustedes por la oportunidad.

Hoy a la noche saco las slides como PDF y te las envío.

Saludos

**Comment by cristofer-dev** [comment]
Gracias @pankas87 
[Dale sabor a tu JS con un poco de Curry(ing)().pdf](https://github.com/Noders/Meetups/files/2003138/Dale.sabor.a.tu.JS.con.un.poco.de.Curry.ing.pdf)
