### ISSUE TITLE
Introducción a service workers

### ISSUE THREAD

**Issue by YerkoPalma** [Noders/Meetups#88]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Yerko Palma

## ¿Cuál es el título de tu charla?

Introducción a service workers

## Danos una descripción de tu charla (20 palabras)
Un repaso rápido por las principales caracteristicas de service workers. Qué son, cómo y por qué usarlos.

## ¿Tienes alguna red social donde podamos contactarte?

Twitter: [@yerko_palma](https://twitter.com/yerko_palma)
Github: [YerkoPalma](https://github.com/YerkoPalma)

## ¿Representas a alguna compañía o empresa?
No.

## ¿Qué tipo de conector tiene tu notebook?

- [x] HDMI
- [ ] Mini DisplayPort
- [x] VGA

## ¿Quieres agregar algo más?
De Junio en adelante por favor, Gracias! :)

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by cristofer-dev** [comment]
Gracias @YerkoPalma por sumarte como charlista y compartir con nosotros tú experiencia! \o/
Te tinca **Julio** ?

**Comment by YerkoPalma** [comment]
Juio estaria perfecto :wink:

**Comment by cristofer-dev** [comment]
Hola @YerkoPalma gracias nuevamente por sumarte como charlista!
Te parece bien presentar en **Jueves 12 de Julio** ?

**Comment by YerkoPalma** [comment]
Si, no hay problema.

**Comment by cristofer-dev** [comment]
Gracias @YerkoPalma Nos vemos en JULIO!

**Comment by YerkoPalma** [comment]
Gracias por la oportunidad! 🎉 
Adjunto los links:

- Repositorio de la presentación: https://github.com/YerkoPalma/service-workers-talk
- Presentación: https://yerkopalma.github.io/service-workers-talk/

**Comment by cristofer-dev** [comment]
Gracias @YerkoPalma por ser parte el meetup y compartir tu experiencia, tu charla estuvo genial y estaremos encantados de recibirte nuevamente cuando gustes.

Enviaremos un resumen con las slides de tu presentación.

Saludos y gracias de parte de la Comunidad de Noders!
