### ISSUE TITLE
Continuous deployment for NodeJs applicaions using Jenkins

### ISSUE THREAD

**Issue by sosongo** [Noders/Meetups#89]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [*] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Renzo Cast

## ¿Cuál es el título de tu charla?
Continuum Deployment with Jenkins

## Danos una descripción de tu charla (20 palabras)
La charla tratara de una breve introducción sobre Jenkins y se hará una demostración de una aplicación siendo deployeada con Jenkins hacia gCloud [GKE]. Así como hablar sobre la experiencia que se ha tenido con Jenkins.

## ¿Tienes alguna red social donde podamos contactarte?
https://www.facebook.com/sosongo

## ¿Representas a alguna compañía o empresa?
Compara Online

## ¿Qué tipo de conector tiene tu notebook?

- [*] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?
Life, the Universe and Everything | Nos vemos en el Meetup!

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by cristofer-dev** [comment]
Gracias @sosongo por sumarte como charlista y compartir con nosotros tú experiencia! \o/
La demo estará orientada a Apps en NodeJS ?

**Comment by enBonnet** [comment]
Master @sosongo ¿Como estas?

¿Tienes inconvenientes de hacer la primera charla del Jueves?

Saludos

**Comment by cristofer-dev** [comment]
@sosongo gracias por ser parte el meetup y compartir tu experiencia, tu charla estuvo genial y estaremos encantados de recibirte nuevamente cuando gustes.

Enviaremos un resumen y nos gustaría incluir las slides de tu presentación, seria genial si nos dejas aquí la información

Saludos y gracias de parte de la Comunidad de Noders!
