### ISSUE TITLE
A complete distributed relay system in JS

### ISSUE THREAD

**Issue by p1nox** [Noders/Meetups#9]
In today's social networking age, we often spend time posting insignificant life updates. But other times, emergency situations arise – times when you really need to get your message across. In emergencies, however, we face obstacles such as low connectivity, blocked networks, no mobile data plans, or not having a smartphone at all. A solution to this problem is a service/platform that allows users to communicate with their relatives via social networks using SMS or BLE protocols. In other words, the ability to use internet without having direct access to it.

The main focus of this talk will be explore the challenges of developing a mobile app using Ionic and a web app using Express, ultimately supporting communication between phones via BLE/SMS, and a central server via HTTP. Messages will spread on this distributed phone network until they reach the central server; from there, they will be relayed to targeted social networks.

This is part of a talk I will be presenting at [JSConf Uruguay 2016](https://jsconf.uy/).

**Comment by Xabadu** [comment]
Awesome @p1nox, thanks! Looking forward to hear this talk. 

This is now confirmed for our next meetup (March, 3rd). Do you need anything from us for your presentation?

**Comment by p1nox** [comment]
Nothing special @Xabadu, just a projector and be able to show my slides ;).

**Comment by p1nox** [comment]
Hey guys! Here you can find my presentation from yesterday's meetup: https://speakerdeck.com/p1nox/a-complete-distributed-relay-system-in-js

And congrats, as usual organisation was awesome :feelsgood: :+1:.
