### ISSUE TITLE
Microservicios orientados a eventos en ComparaOnline

### ISSUE THREAD

**Issue by jacobparra** [Noders/Meetups#90]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Jacob Parra

## ¿Cuál es el título de tu charla?
Microservicios orientado a eventos en ComparaOnline

## Danos una descripción de tu charla (20 palabras)
La charla trata sobre los problemas que tuvimos en ComparaOnline para comunicar múltiples microservicios entre si. Principalmente comentaré como pasamos a una arquitectura de microservicios basada en eventos, usando Kafka como herramienta central de comunicación.

## ¿Tienes alguna red social donde podamos contactarte?

https://github.com/jacobparra/

## ¿Representas a alguna compañía o empresa?
ComparaOnline

## ¿Qué tipo de conector tiene tu notebook?

- [x] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by cristofer-dev** [comment]
Genial @jacobparra por sumarte como charlista y compartir con nosotros tú experiencia! \o/
Estamos coordinando fecha y lugar para los próximos meetups, apenas tengamos la información te confirmamos!

**Comment by enBonnet** [comment]
Hola @jacobparra espero que estés muy bien, te escribo para comentarte que el próximo meetup en las oficinas de ComparaOnline será el en Octubre, ya lo confirme con María. Respecto a eso quería consultarte si de igual forma ¿Quieres dar tu charla para Agosto o la dejamos agendada para Octubre?

Lo que se te haga más cómodo, un abrazo y de nuevo gracias por sumarte :+1:

**Comment by cristofer-dev** [comment]
Hola @jacobparra te viene bien **Agosto** para presentar tu charla ??

**Comment by jacobparra** [comment]
Hola @cristofer-dev y @enBonnet. Me gustaría presentar en octubre, cuando se haga el meetup en ComparaOnline. Así tenemos un representante de la empresa en el meetup.

**Comment by cristofer-dev** [comment]
Genial @jacobparra! Agendamos para **Octubre**

**Comment by enBonnet** [comment]
Máster @jacobparra estamos confirmando ¿Aún tienes la disponibilidad de hacer la charla el 11 de octubre en las oficinas de ComparaOnline? Saludos

**Comment by jacobparra** [comment]
@enBonnet Hola! Si, para el 11 de octubre está bien. 👍
