### ISSUE TITLE
Back to the Browser - Web Components

### ISSUE THREAD

**Issue by highercomve** [Noders/Meetups#91]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [X] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Sergio Marin

## ¿Cuál es el título de tu charla?
Back to the Browser - Web components
Hablemos de web components como crear webcomponents en VanillaJS y porque web components es el futuro para la plataforma web

## Danos una descripción de tu charla (20 palabras)
Hoy en dia tendemos a escribir components para nuestras aplicaciones web pero dentro del scope de un framework siendo que la plataforma web y los browser cada dia tienen mas soporte a web components de manera nativa. Vamos a hablar un poco mas de como es el soporte nativo.

## ¿Tienes alguna red social donde podamos contactarte?
@highercomve (todas las redes sociales)

## ¿Qué tipo de conector tiene tu notebook?

- [ X ] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?
Borrador de la presentación en ingles (No esta lista)
https://slides.com/highercomve/web-components

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by cristofer-dev** [comment]
Gracias @highercomve por sumarte como charlista y compartir una vez más con nosotros tú experiencia! \o/
Te parece bien presentar en **Agosto** ?

**Comment by highercomve** [comment]
Por supuesto @cristofer_dev agosto está perfecto.

Saludos
