### ISSUE TITLE
Paralelizando promesas: concurrencia, throttling y manejo de errores

### ISSUE THREAD

**Issue by lupomontero** [Noders/Meetups#92]
## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?

Lupo Montero

## ¿Cuál es el título de tu charla?

_Paralelizando promesas_: concurrencia, throttling y manejo de errores

## Danos una descripción de tu charla (20 palabras)

Si necesitamos ejecutar muchas tareas asíncronas (imagina un arreglo de promesas) se convierte en una gran limitación no poder controlar la concurrencia de las operaciones con `Promise.all`. En esta charla veremos como podemos agregar la noción de concurrencia, throttling y manejo de errores para grupos de tareas modeladas como promesas.

Esta propuesta de charla está basada en este [post](https://medium.com/laboratoria-how-to/paralelizando-promesas-372894c1d21f) y una charla anterior en un meetup de LimaJS. En esta ocasión me gustaría revisitar el tema y presentarlo en formato _live coding_.

## ¿Tienes alguna red social donde podamos contactarte?

* [GitHub](https://github.com/lupomontero)
* [Twitter](https://twitter.com/lupomontero)
* [Medium](https://medium.com/lupomontero)

## ¿Representas a alguna compañía o empresa?

Trabajo para [Laboratoria](http://www.laboratoria.la/). Co-organizo [LimaJS](https://limajs.org/). Las opiniones son mías.

## ¿Qué tipo de conector tiene tu notebook?

- [x] HDMI
- [ ] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?

No vivo en Santiago, pero voy de vez en cuando y estoy planeando estar para el [meetup del 13 de Septiembre](https://www.meetup.com/NodersJS/events/snrpwpyxmbrb/). Así que mi propuesta de _keynote_ sería para esa fecha.

**Comment by cristofer-dev** [comment]
Gracias @lupomontero  por sumarte como charlista y compartir con nosotros tú experiencia! \o/
Agendado para **Septiembre** !

**Comment by enBonnet** [comment]
Hello master @lupomontero estamos confirmando para el próximo meetup, podemos contar contigo para el jueves 13 de septiembre? Saludos

**Comment by lupomontero** [comment]
Sí, jueves 13 de septiembre confirmado :heavy_check_mark:

**Comment by cristofer-dev** [comment]
@lupomontero gracias por ser parte el meetup y compartir tu experiencia, tu charla estuvo genial y estaremos encantados de recibirte nuevamente cuando gustes.

Enviaremos un resumen y nos gustaría incluir las slides de tu presentación, seria genial si nos dejas aquí la información

Saludos y gracias de parte de la Comunidad de Noders!

**Comment by lupomontero** [comment]
Hola @cristofer-dev, un gusto participar en el meetup. Gracias por todo!

Ahí dejo el link a los slides:

https://docs.google.com/presentation/d/e/2PACX-1vTTXUEP7CCckZ4gefsnLe0DeYIbigf-7WwGrq76_VwTlp9qzV2xeB4gQZjZ2NYehViAeIjnnS09Mw2h/pub?start=false&loop=false&delayms=3000

:rocket:
