### ISSUE TITLE
Charla Orionjs

### ISSUE THREAD

**Issue by nicolaslopezj** [Noders/Meetups#96]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?

Nicolás López

## ¿Cuál es el título de tu charla?

Orionjs: un nuevo framework de nodejs made in Chile 

## Danos una descripción de tu charla (20 palabras)

Sería una introducción al framework, aspectos generales, como empezar, filosofía, porque se hizo, etc

## ¿Tienes alguna red social donde podamos contactarte?

GitHub 

## ¿Representas a alguna compañía o empresa?

Orionsoft

## ¿Qué tipo de conector tiene tu notebook?

- [ ] HDMI
- [ ] Mini DisplayPort
- [ ] VGA
- [x] USB C

## ¿Quieres agregar algo más?

Que fechas se hacen estos eventos?

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by nicolaslopezj** [comment]
https://orionjs.com/

**Comment by enBonnet** [comment]
Hola @nicolaslopezj muchas gracias por querer compartir con nosotros esta charla!
Te estaremos avisando por este medio en que fecha

**Comment by nicolaslopezj** [comment]
Dale, o me pueden enviar un mail a nicolaslopezj@me.com

**Comment by enBonnet** [comment]
Hola @nicolaslopezj ¿te parece bien hacer tu charla el 11 de octubre?

**Comment by nicolaslopezj** [comment]
Si puedo. Cuanto gente va a estos meetups?

**Comment by enBonnet** [comment]
¡Entre 30 y 40 personas máster!

Wojo! Que bueno que si puedas te vamos a agendar para el meetup de octubre entonces, será en las oficinas de ComparaOnline.

**Comment by nicolaslopezj** [comment]
Donde quedan? A qué hora empieza?

**Comment by enBonnet** [comment]
Cerca del metro Manuel Montt, no tengo la dirección a mano. Pero estará cuando publique el evento en meetups.

**Comment by nicolaslopezj** [comment]
Tienen alguna invitación o imagen para compartir el evento?

**Comment by nicolaslopezj** [comment]
Cómo están promocionando el evento?

**Comment by cristofer-dev** [comment]
Hola @nicolaslopezj, gusto de saludarte, lamentamos la demora en la respuesta.

El link del evento es https://www.meetup.com/es-ES/NodersJS/events/mszzgqyxnbpb/

Gracias por sumarte como charlista y compartir con nosotros tú experiencia! \o/
