### ISSUE TITLE
Procedural Content Generation para Juegos

### ISSUE THREAD

**Issue by pctroll** [Noders/Meetups#98]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/Noders/code_of_conduct) - [https://github.com/Noders/code_of_conduct](https://github.com/Noders/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (20 a 30 minutos)
- [ ] Lightning Talk (+- 5 minutos)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Jorge Palacios

## ¿Cuál es el título de tu charla?

Procedural Content Generation para Juegos

## Danos una descripción de tu charla (20 palabras)

Veremos 2 técnicas de generación de contenidos para juegos a profundidad: algoritmo genético y BSP (binary space partitioning)

## ¿Tienes alguna red social donde podamos contactarte?

Twitter: @pctroll

## ¿Representas a alguna compañía o empresa?
No, yo mismo.

## ¿Qué tipo de conector tiene tu notebook?

- [x] HDMI
- [ ] Mini DisplayPort
- [ ] VGA
- [x] USB-C

## ¿Quieres agregar algo más?
Quisiera presentar la charla en Diciembre 2018 =DDDDDD <3

-----------
> Muchas Gracias! 
> El equipo de @Noders/meetup

**Comment by rodrigoAdones** [comment]
Hola Jorge

Gracias por interesarte dar una charla en el meetup de Noders.

Este jueves tenemos planificado realizar el meetup, y nos gustaría que expusieras en esta ocasión.

Por favor, déjanos saber si te es posible presentar

Saludos

**Comment by pctroll** [comment]
Hola equipo, ¿cómo están?

¿Podríamos agendar esta charla para Febrero? por motivos laborales no me da tiempo de preparar bien la charla para el jueves, y no quisiera dar una charla a medias sin demo.

¿Es posible? Espero que sí =D

**Comment by rodrigoAdones** [comment]
Dale, no hay problema

Para febrero entonces 👍

**Comment by rodrigoAdones** [comment]
Hola Jorge

Espero estes bien.

Te quería informar que movimos el meetup para el jueves 21 de Febrero.

Te parece esa fecha para hacer tu presentación?

Nos avisas por favor si tienes algún inconveniente o estas de acuerdo

Saludos

**Comment by pctroll** [comment]
Sí, me queda perfecto!

Kind regards,

*Jorge Palacios*

**Comment by rodrigoAdones** [comment]
Perfecto

Estamos en contacto

Saludos

**Comment by rodrigoAdones** [comment]
Jorge, disculpa pero no podremos realizar el meetup este mes.

Te pido mil disculpas por cualquier inconveniente provocado por la cancelación.

Quería saber si puedes dar la charla en el meetup de Marzo, quedo atento a tu respuesta.

Saludos

**Comment by pctroll** [comment]
Sí, no hay problema!

Kind regards,

*Jorge Palacios*

**Comment by rodrigoAdones** [comment]
Buenas

Ya confirmamos el meetup para el 14 de marzo, sera en las oficinas de ComparaOnline

Puedes exponer en esa fecha? espero tu confirmación

Saludos

**Comment by pctroll** [comment]
Hola Rodrigo,

Sí. Ningún problema =) Nos vemos el 14.

Kind regards,

*Jorge Palacios*

**Comment by rodrigoAdones** [comment]
Genial Jorge!

Nos vemos el 14.

Saludos.
